{
  "hash": "3b75e60e0fe732f9d55c6872d0101dea",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1\"\nauthor: \"Ananya Pujary\"\ndescription: \"Reading in data and creating a post\"\ndate: \"08/15/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n  - railroad\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nReading in data and creating a post\n\n## Read in the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n```\n:::\n\n\n## Describe the data\n\n*Using a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).*\n\nI'll be working with the 'railroad_2012_clean_county.csv' dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(railroad) #describing the 'railroad' dataset's dimensions\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\n\nFrom this command, we learn that the 'railroad_2012_clean_county.csv' dataset has 3 columns and 2930 rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n\n```{.r .cell-code}\nhead(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\n\nThe columns in 'railroad' are: 'state' (datatype: character), 'county'(datatype: character), and 'total_employees'(datatype: double class - numeric values with decimal points). These data were probably collected as part of a large-scale survey of the number of railroad employees by county and state in the United States.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_arranged <- railroad %>%\n  arrange(desc(total_employees)) # arranging data to find the county with the most number of employees\nhead(railroad_arranged)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county           total_employees\n  <chr> <chr>                      <dbl>\n1 IL    COOK                        8207\n2 TX    TARRANT                     4235\n3 NE    DOUGLAS                     3797\n4 NY    SUFFOLK                     3685\n5 VA    INDEPENDENT CITY            3249\n6 FL    DUVAL                       3073\n```\n:::\n:::\n\n\nCook county in Illinois has the highest number of railroad employees (8207).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroads<- railroad %>%\n  group_by(state) %>%  # grouping the data by state\n  select(total_employees) %>% # looking only at the 'total_employees' column\n  summarize_all(sum, na.rm=TRUE)%>% # adding the number of employees in the counties state-wise\n  arrange(desc(total_employees)) # arranging the states from highest to lowest number of employees\n\nhead(railroads)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  state total_employees\n  <chr>           <dbl>\n1 TX              19839\n2 IL              19131\n3 NY              17050\n4 NE              13176\n5 CA              13137\n6 PA              12769\n```\n:::\n:::\n\n\nTexas has the most railroad employees (19839) and the Armed Forces Pacific has the least (1).\n",
    "supporting": [
      "challenge1_AnanyaPujary_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}