{
  "hash": "a0adec89c848eab25eb77939e692388f",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3\"\nauthor: \"Ananya Pujary\" \ndescription: \"Tidy Data: Pivoting\"\ndate: \"08/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - animal_weight\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nlibrary(skimr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in data\n\nI'll be reading in the 'animal_weight' dataset.\n\n::: {.cell}\n\n```{.r .cell-code}\nanimal_weight<-read_csv(\"_data/animal_weight.csv\",\n                        show_col_types = FALSE)\n```\n:::\n\n\n### Briefly describe the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(animal_weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  9 17\n```\n:::\n\n```{.r .cell-code}\ncolnames(animal_weight) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"IPCC Area\"          \"Cattle - dairy\"     \"Cattle - non-dairy\"\n [4] \"Buffaloes\"          \"Swine - market\"     \"Swine - breeding\"  \n [7] \"Chicken - Broilers\" \"Chicken - Layers\"   \"Ducks\"             \n[10] \"Turkeys\"            \"Sheep\"              \"Goats\"             \n[13] \"Horses\"             \"Asses\"              \"Mules\"             \n[16] \"Camels\"             \"Llamas\"            \n```\n:::\n:::\n\nThe data chosen seems to describe the average weights of different animals (dairy and non-dairy cattle, chickens, ducks, etc.) across global regions (Africa, Latin America, Middle East, etc.). It has 9 rows and 17 columns, of which the $n=9$ rows indicate the region name and $k=16$ columns the type of animal. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(animal_weight)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |              |\n|:------------------------|:-------------|\n|Name                     |animal_weight |\n|Number of rows           |9             |\n|Number of columns        |17            |\n|_______________________  |              |\n|Column type frequency:   |              |\n|character                |1             |\n|numeric                  |16            |\n|________________________ |              |\n|Group variables          |None          |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|IPCC Area     |         0|             1|   4|  19|     0|        9|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable      | n_missing| complete_rate|   mean|     sd|    p0|   p25|   p50|   p75|  p100|hist  |\n|:------------------|---------:|-------------:|------:|------:|-----:|-----:|-----:|-----:|-----:|:-----|\n|Cattle - dairy     |         0|             1| 425.44| 140.39| 275.0| 275.0| 400.0| 550.0| 604.0|▇▅▁▂▇ |\n|Cattle - non-dairy |         0|             1| 298.00| 116.26| 110.0| 173.0| 330.0| 391.0| 420.0|▂▃▁▃▇ |\n|Buffaloes          |         0|             1| 370.56|  28.33| 295.0| 380.0| 380.0| 380.0| 380.0|▁▁▁▁▇ |\n|Swine - market     |         0|             1|  39.22|  10.79|  28.0|  28.0|  45.0|  50.0|  50.0|▇▁▁▂▇ |\n|Swine - breeding   |         0|             1| 116.44|  84.19|  28.0|  28.0| 180.0| 180.0| 198.0|▆▁▁▁▇ |\n|Chicken - Broilers |         0|             1|   0.90|   0.00|   0.9|   0.9|   0.9|   0.9|   0.9|▁▁▇▁▁ |\n|Chicken - Layers   |         0|             1|   1.80|   0.00|   1.8|   1.8|   1.8|   1.8|   1.8|▁▁▇▁▁ |\n|Ducks              |         0|             1|   2.70|   0.00|   2.7|   2.7|   2.7|   2.7|   2.7|▁▁▇▁▁ |\n|Turkeys            |         0|             1|   6.80|   0.00|   6.8|   6.8|   6.8|   6.8|   6.8|▁▁▇▁▁ |\n|Sheep              |         0|             1|  39.39|  10.80|  28.0|  28.0|  48.5|  48.5|  48.5|▆▁▁▁▇ |\n|Goats              |         0|             1|  34.72|   4.48|  30.0|  30.0|  38.5|  38.5|  38.5|▆▁▁▁▇ |\n|Horses             |         0|             1| 315.22|  73.26| 238.0| 238.0| 377.0| 377.0| 377.0|▆▁▁▁▇ |\n|Asses              |         0|             1| 130.00|   0.00| 130.0| 130.0| 130.0| 130.0| 130.0|▁▁▇▁▁ |\n|Mules              |         0|             1| 130.00|   0.00| 130.0| 130.0| 130.0| 130.0| 130.0|▁▁▇▁▁ |\n|Camels             |         0|             1| 217.00|   0.00| 217.0| 217.0| 217.0| 217.0| 217.0|▁▁▇▁▁ |\n|Llamas             |         0|             1| 217.00|   0.00| 217.0| 217.0| 217.0| 217.0| 217.0|▁▁▇▁▁ |\n:::\n:::\n\nThere are no missing values in this dataset. Overall, dairy cattle seem to have the highest average weight (425.44) and broiler chickens have the lowest (0.9).\n\nI plan to pivot it because it seems that the selected animals are recurring categories in all of the regions. $k-3$ variables will be pivoted and put in a new column.\n\nHence, the pivoted dataset would have 144 rows and 3 columns ('IPCC Area','Animal Type', 'Weight').\n\n### Challenge: Describe the final dimensions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# existing rows/cases\nnrow(animal_weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9\n```\n:::\n\n```{.r .cell-code}\n# existing columns/cases\nncol(animal_weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17\n```\n:::\n\n```{.r .cell-code}\n#expected rows/cases\nnrow(animal_weight) * (ncol(animal_weight)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 144\n```\n:::\n\n```{.r .cell-code}\n# expected columns \n1 + 2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3\n```\n:::\n:::\n\n\nThere are 9 existing rows and 17 existing columns. The expected rows are 144 and expected columns are 3.\n\n### Challenge: Pivot the Chosen Data \n\n\n::: {.cell}\n\n```{.r .cell-code}\nanimal_weight_pivoted <- pivot_longer(animal_weight,\n                         col = c('Cattle - dairy', 'Cattle - non-dairy', 'Buffaloes', 'Swine - market', 'Swine - breeding', 'Chicken - Broilers', 'Chicken - Layers', 'Ducks', 'Turkeys', 'Sheep', 'Goats', 'Horses', 'Asses', 'Mules', 'Camels', 'Llamas'), names_to = 'Animal Type', values_to = 'Weight')\nanimal_weight_pivoted\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 144 × 3\n   `IPCC Area`         `Animal Type`      Weight\n   <chr>               <chr>               <dbl>\n 1 Indian Subcontinent Cattle - dairy      275  \n 2 Indian Subcontinent Cattle - non-dairy  110  \n 3 Indian Subcontinent Buffaloes           295  \n 4 Indian Subcontinent Swine - market       28  \n 5 Indian Subcontinent Swine - breeding     28  \n 6 Indian Subcontinent Chicken - Broilers    0.9\n 7 Indian Subcontinent Chicken - Layers      1.8\n 8 Indian Subcontinent Ducks                 2.7\n 9 Indian Subcontinent Turkeys               6.8\n10 Indian Subcontinent Sheep                28  \n# … with 134 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\ndim(animal_weight_pivoted)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 144   3\n```\n:::\n:::\n\nThe dimensions of the pivoted data, as predicted, are 144 rows and 3 columns. The new case created is 'Animal Type'. Overall, pivoting made the data easier to understand since we can now find the weight of a certain animal from a particular region.\n",
    "supporting": [
      "challenge3_AnanyaPujary_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}