{
  "hash": "5d762d325b8b027442e941bc7c332d75",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Mani Shanker Kamarapu\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"08/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - FAOSTAT_cattle_dairy.csv\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in the Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFAOSTAT_cattle_dairy <- read_csv(\"_data/FAOSTAT_cattle_dairy.csv\")\nView(FAOSTAT_cattle_dairy)\n```\n:::\n\n\nAs we read the data, there are many interesting variables and a lot of observations based on yearly analysis of the various cattle products.\n\n## Describe the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(FAOSTAT_cattle_dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 36449    14\n```\n:::\n:::\n\n\nWe can see that there are 36449 rows and 14 columns in the data. We can see from observations from different variables that \"Value\" variable is pretty much the only real valuable data we are getting from this data set and remaining variables are either unchanged(Domain and Item) or grouping variables(Area, Element, Year and Flag) which can be used to summarize data and find the categories we are interested in and also can be used to find specific information we need and let's try to get to some more useful info using some other functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(FAOSTAT_cattle_dairy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Domain Code\"      \"Domain\"           \"Area Code\"        \"Area\"            \n [5] \"Element Code\"     \"Element\"          \"Item Code\"        \"Item\"            \n [9] \"Year Code\"        \"Year\"             \"Unit\"             \"Value\"           \n[13] \"Flag\"             \"Flag Description\"\n```\n:::\n:::\n\n\nThese are the variables available in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(filter(select(FAOSTAT_cattle_dairy, Value)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Value          \n Min.   :        7  \n 1st Qu.:     7849  \n Median :    43266  \n Mean   :  4410235  \n 3rd Qu.:   700000  \n Max.   :683217055  \n NA's   :74         \n```\n:::\n:::\n\n\nIt is the summary of the Value variable of the data set which is the only real data variable in data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nArea_num <- distinct(FAOSTAT_cattle_dairy, Area)\nElement_num <- distinct(FAOSTAT_cattle_dairy, Element)\nYear_num <- distinct(FAOSTAT_cattle_dairy, Year)\nFlag_num <- distinct(FAOSTAT_cattle_dairy, Flag)\nDistinct_count <- c(nrow(Area_num), nrow(Element_num), nrow(Year_num), nrow(Flag_num))\nDistinct_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 232   3  58   7\n```\n:::\n:::\n\n\nWe can observe that data set has the data from 1961-2018 on 3 elements at 232 different areas.\n\nI am interested in finding in more information about Flag and how it corresponds to the description they have given and can we group the values by using it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFLag_info <- FAOSTAT_cattle_dairy %>%\n  select(Flag,`Flag Description`)\nunique(FLag_info)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 2\n  Flag  `Flag Description`                                                      \n  <chr> <chr>                                                                   \n1 F     FAO estimate                                                            \n2 Fc    Calculated data                                                         \n3 <NA>  Official data                                                           \n4 *     Unofficial figure                                                       \n5 Im    FAO data based on imputation methodology                                \n6 M     Data not available                                                      \n7 A     Aggregate, may include official, semi-official, estimated or calculated…\n```\n:::\n:::\n\n\nFrom the above observation we got to know there are 7 types of flags and it is based on data provided and type of data and values they are and how is has been taken.\n\n## Provide Grouped Summary Statistics\n\n#### Area and Element wise analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAE_analysis <- FAOSTAT_cattle_dairy %>%\n  group_by(Area, Element) %>%\n  summarise(mean_value=mean(Value, na.rm = TRUE), median_value=median(Value, na.rm = TRUE), sd_value=sd(Value, na.rm = TRUE), min_value=min(Value, na.rm = TRUE), max_value=max(Value, na.rm = TRUE), IQR_value=IQR(Value, na.rm = TRUE))\nAE_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 695 × 8\n# Groups:   Area [232]\n   Area        Element      mean_value median_…¹ sd_va…² min_v…³ max_v…⁴ IQR_v…⁵\n   <chr>       <chr>             <dbl>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1 Afghanistan Milk Animals   1790863.  1150000   1.08e6  7   e5  4.05e6  1.57e6\n 2 Afghanistan Production      914876.   600000   5.01e5  3   e5  1.87e6  8.86e5\n 3 Afghanistan Yield             5246.     5128   9.06e2  3.59e3  7.33e3  6.35e2\n 4 Africa      Milk Animals  37629052. 33173522.  1.75e7  1.70e7  7.13e7  3.00e7\n 5 Africa      Production    18949137. 15058869   1.02e7  7.65e6  3.68e7  1.88e7\n 6 Africa      Yield             4869.     4600   4.39e2  4.31e3  5.84e3  6.93e2\n 7 Albania     Milk Animals    288774.   284650   1.13e5  1.17e5  4.88e5  1.92e5\n 8 Albania     Production      521367.   392500   3.37e5  7.83e4  9.83e5  6.78e5\n 9 Albania     Yield            16197     13857   6.61e3  6.35e3  2.84e4  8.11e3\n10 Algeria     Milk Animals    659719.   640000   2.50e5  2.63e5  1.11e6  4.14e5\n# … with 685 more rows, and abbreviated variable names ¹​median_value,\n#   ²​sd_value, ³​min_value, ⁴​max_value, ⁵​IQR_value\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nAs per the analysis, in each area the we have three kinds of elements and there are a lot of variations and mean value is not dependent to element itself in any area but it differs in each area and we can get a deeper understanding when we analyse the area and element separately.\n\n#### Year and Element wise analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nYE_analysis <- FAOSTAT_cattle_dairy %>%\n  group_by(Year, Element) %>%\n  summarise(mean_value=mean(Value, na.rm = TRUE), median_value=median(Value, na.rm = TRUE), sd_value=sd(Value, na.rm = TRUE), min_value=min(Value, na.rm = TRUE), max_value=max(Value, na.rm = TRUE), IQR_value=IQR(Value, na.rm = TRUE))\nYE_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 174 × 8\n# Groups:   Year [58]\n    Year Element      mean_value median_value  sd_value min_va…¹ max_v…² IQR_v…³\n   <dbl> <chr>             <dbl>        <dbl>     <dbl>    <dbl>   <dbl>   <dbl>\n 1  1961 Milk Animals   3582516.       200550 15152245.        8  1.77e8  1.23e6\n 2  1961 Production     6335891.       100368 28456161.        7  3.14e8  1.74e6\n 3  1961 Yield            11949.         8812     9905.     1200  4.29e4  1.41e4\n 4  1962 Milk Animals   3567116.       200850 15117111.       17  1.77e8  1.21e6\n 5  1962 Production     6384721.       100000 28667301.       23  3.16e8  1.76e6\n 6  1962 Yield            12105.         8899    10173.     1200  4.43e4  1.41e4\n 7  1963 Milk Animals   3578137.       219550 15189434.       20  1.77e8  1.21e6\n 8  1963 Production     6319684.       102500 28305726.       20  3.13e8  1.78e6\n 9  1963 Yield            12147.         9051    10241.     1191  4.59e4  1.44e4\n10  1964 Milk Animals   3554094.       215650 15090377.       25  1.76e8  1.25e6\n# … with 164 more rows, and abbreviated variable names ¹​min_value, ²​max_value,\n#   ³​IQR_value\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nAs per the data, we can say that the elements has been increased by passing year, there are some fluctuations in between but there is an overall increase by the year.\n\n#### Element-wise analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE_analysis <- FAOSTAT_cattle_dairy %>%\n  group_by(Element) %>%\n  summarise(mean_value=mean(Value, na.rm = TRUE), median_value=median(Value, na.rm = TRUE), sd_value=sd(Value, na.rm = TRUE), min_value=min(Value, na.rm = TRUE), max_value=max(Value, na.rm = TRUE), IQR_value=IQR(Value, na.rm = TRUE)) %>%\n  arrange(desc(mean_value))\nE_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 7\n  Element      mean_value median_value  sd_value min_value max_value IQR_value\n  <chr>             <dbl>        <dbl>     <dbl>     <dbl>     <dbl>     <dbl>\n1 Production     9001419.       295500 40268994.         7 683217055   2736860\n2 Milk Animals   4205410.       295000 18041595.         8 276573845   1525233\n3 Yield            19329.        13218    19361.       923    134121     21367\n```\n:::\n:::\n\n\nAs per the above observation, the mean value of the production is maximum and yield is the minimum. It shows that the production value is more with the less yield and it leads to an overall profit.\n\n#### Area-wise analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA_analysis <- FAOSTAT_cattle_dairy %>%\n  group_by(Area) %>%\n  summarise(mean_value=mean(Value, na.rm = TRUE), median_value=median(Value, na.rm = TRUE), sd_value=sd(Value, na.rm = TRUE), min_value=min(Value, na.rm = TRUE), max_value=max(Value, na.rm = TRUE), IQR_value=IQR(Value, na.rm = TRUE)) %>%\n  arrange(desc(mean_value))\nA_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 232 × 7\n   Area                     mean_value median_…¹ sd_va…² min_v…³ max_v…⁴ IQR_v…⁵\n   <chr>                         <dbl>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1 World                    230162236.    2.20e8  2.02e8   17662  6.83e8  3.87e8\n 2 Europe                    99143192.    8.26e7  9.82e7   21977  2.80e8  2.09e8\n 3 Americas                  56060267.    4.51e7  5.50e7   22342  1.84e8  9.12e7\n 4 Asia                      48224349.    3.71e7  5.08e7    6034  2.13e8  7.49e7\n 5 Eastern Europe            45406646.    4.82e7  4.33e7   16644  1.40e8  7.46e7\n 6 USSR                      42870195.    4.18e7  3.68e7   15900  1.08e8  8.09e7\n 7 Western Europe            30380343.    1.67e7  3.27e7   30476  8.74e7  7.21e7\n 8 Northern America          29827044.    1.14e7  3.49e7   32302  1.06e8  6.43e7\n 9 Southern Asia             28165903.    2.50e7  2.75e7    3824  1.17e8  4.64e7\n10 United States of America  26633354.    1.00e7  3.15e7   33068  9.87e7  5.61e7\n# … with 222 more rows, and abbreviated variable names ¹​median_value,\n#   ²​sd_value, ³​min_value, ⁴​max_value, ⁵​IQR_value\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nAs per the analysis, Europe has the highest cattle dairy and British Virgin Islands has the minimum, we can say none. \n\n#### Year-wise analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY_analysis <- FAOSTAT_cattle_dairy %>%\n  group_by(Year) %>%\n  summarise(mean_value=mean(Value, na.rm = TRUE), median_value=median(Value, na.rm = TRUE), sd_value=sd(Value, na.rm = TRUE), min_value=min(Value, na.rm = TRUE), max_value=max(Value, na.rm = TRUE), IQR_value=IQR(Value, na.rm = TRUE)) %>%\n  arrange(desc(mean_value))\nY_analysis\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 58 × 7\n    Year mean_value median_value  sd_value min_value max_value IQR_value\n   <dbl>      <dbl>        <dbl>     <dbl>     <dbl>     <dbl>     <dbl>\n 1  2017   5682309.       80522. 33349614.        20 677670685   958680 \n 2  2018   5654115.       79029  33488177.        21 683217055   938124 \n 3  2016   5617407.       77378. 32809823.        20 665596536   981852.\n 4  2015   5586308.       78062. 32577146.        20 661430554   964494 \n 5  2014   5534018.       77490  32246947.        20 655245580   947544.\n 6  2013   5411995.       75958. 31386003.        20 635379383   964509 \n 7  2012   5372784.       74057  31140061.        20 630244839   946680 \n 8  2011   5287165.       71750  30561395.        20 616177381   953420.\n 9  2010   5185483.       70586  29911569.        20 601868328   928111 \n10  2009   5088955.       70375  29357924.         9 590471016   895700 \n# … with 48 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nAs per the data, the cattle dairy production has been increased by the passing year, there are some fluctuations in middle but the overall it is increasing, we can see from the data that the increase is nearly 85 percentage from 1961 to 2018.\n\n### Explain and Interpret\n\nI chose Element, Area and Year subgroups from data set. The reason for choosing them is there importance in analysis and also tried to analysis using two variables to know the dependency of values on different variables. So I have done Area and Element wise analysis, Year and Element wise analysis, Element-wise analysis, Area-wise analysis and Year-wise analysis. Conclusion to my analysis would be Europe has the highest of the cattle dairy and the production of the dairy is increasing gradually as by the year. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}