{
  "hash": "86adeeea10e40626785fb758fc727b33",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8\"\nauthor: \"Ananya Pujary\"\ndescription: \"Joining Data\"\ndate: \"08/25/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n  - faostat\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(summarytools)\nlibrary(dplyr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in data\n\nReading in the faostat datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfaostat_egg <- read_csv(\"_data/FAOSTAT_egg_chicken.csv\")\nfaostat_livestock <- read_csv(\"_data/FAOSTAT_livestock.csv\")\nfaostat_cattle <- read_csv(\"_data/FAOSTAT_cattle_dairy.csv\")\nfaostat_country <- read_csv (\"_data/FAOSTAT_country_groups.csv\")\n```\n:::\n\n\n### Briefly describe the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(summarytools::dfSummary(faostat_egg, varnumbers = FALSE, plain.ascii = FALSE, graph.magnif = 0.50, style = \"grid\", valid.col = FALSE), \n      method = 'render', table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>faostat_egg</h4>\n<strong>Dimensions</strong>: 38170 x 14\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">Domain Code\n[character]</td>\n      <td align=\"left\">1. QL</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCKe8pGHAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM0KzAwOjAwIAuIEwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNCswMDowMFFWMK8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Domain\n[character]</td>\n      <td align=\"left\">1. Livestock Primary</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCKe8pGHAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM0KzAwOjAwIAuIEwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNCswMDowMFFWMK8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 771.1 (1709.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 143 &le; 5504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 145 (2.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">245 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCKe8pGHAAAAnElEQVRo3u3awQmAMAxGYSvd0R10HruDU+pFMBV7ajF/4L2LiCAf2JxiOif1Zm8AxH/K9qaYg7klT5adkFw/Wu7r4el7FeBDQ4SoEkSIKkGEqBJEiCpBhKgSRIgqQYSoEkSIKkGEqBJEiCoFIOb+V/S0V+vw772jM/HZOrb3jgE+NMQRuZ9FmxkeMzjJjlSR+d1kbRE1C3AWIY7oAk48DhCx18cNAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM0KzAwOjAwIAuIEwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNCswMDowMFFWMK8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Afghanistan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Albania</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Algeria</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. American Samoa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Americas</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Angola</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Antigua and Barbuda</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Argentina</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 235 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">174</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">36430</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">95.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFQAAACJCAQAAAAYwte7AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCKe8pGHAAAA9UlEQVR42u3VQQrCQBAFUUdyR0/mIXLKZNsTcCNNpj6pciWCPNLiH8cro/dqgNBlHeX1hf1gqy3miQoVSk+oUHox0FFXc6zWXKq26YnStr4Wc3qhQukJFUovBurWdxdzeqFC6QkVSi8G6tZ3F3N6oULpCRVKLwbq1ncXc3qhQukJFUovc0LJufVC6QkVSk9od5lb74QKBSZUKD2hj4W69d3FnF6oUHpChdKLgbr13cWcXqhQekKF0ouBuvXdxZxeqFB6QoXSi4HGbP1WP8BtfXly2/zJZzWttE/vYn6jQoXSE9rd5X90/+9bbmjQxuhXMacX2t0JaqY1+c7+jGoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzQrMDA6MDAgC4gTAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM0KzAwOjAwUVYwrwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5411.4 (80.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5313 &le; 5410 &le; 5510</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 197 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5313</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12679</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5410</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12651</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.1%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5510</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12840</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAAAqCAQAAAB19uFeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAbElEQVRIx2P8z0A9wERFswaxYSzInGlkBGAWIw7DGBjCSTRqJe28OWrYcDIMLZ2tJM8UKGBETvSMZBiArB/FZVNJzk7ZKPZTlJ3QA2XwxuaoYcPJsGGbN1FdMFrVjRo25AyjXd4cVN4cvIYBAKnqEO+spkjRAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAwhnyDpwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMPchOxsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Laying</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Production</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Yield</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12679</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12840</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12651</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAAAqCAQAAAB19uFeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAaUlEQVRIx2P8z0A9wERFswaxYSzInGlkBGAWIw7DGBjCSTRqJe28OWrYcDIMLZ2tJM8UKGBETvSMZBiArB/FZVPJKY9Gs9OoYUPZsGGbN7NR7Kcob6IHyuCNzVHDhpNhtMubg8qbg9cwACenEO8OA5zVAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAwhnyDpwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMPchOxsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item Code\n[numeric]</td>\n      <td align=\"left\">1 distinct value</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1062</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAwhnyDpwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMPchOxsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item\n[character]</td>\n      <td align=\"left\">1. Eggs, hen, in shell</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38170</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAwhnyDpwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMPchOxsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.5 (16.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAv0lEQVRo3u3ZUQ6CMBBFUWrYY/eg68E9sEr5ggxJm7Rmat/Ee7/AKJy0NAFJn0W9x2wAxN+02p007DRb0yX/ugD262vLTz1g+draq9vl3In38ToB+xdHGkZcGsalrwDLJQCxMtFtK3ACsXcF5uKnQ4k+K9C7ANciRIgqQYSoEkSPhj4Y9GZuY8xjlBSxfBMTYKIhQlQJIkSVIEJUCSJElSBCVAkiRJUg/gkx2Zd9b5k3f0/zz1iSUVULMNEQPToAXagcaEQrk+4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzUrMDA6MDCGfIOnAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAw9yE7GwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.5 (16.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAv0lEQVRo3u3ZUQ6CMBBFUWrYY/eg68E9sEr5ggxJm7Rmat/Ee7/AKJy0NAFJn0W9x2wAxN+02p007DRb0yX/ugD262vLTz1g+draq9vl3In38ToB+xdHGkZcGsalrwDLJQCxMtFtK3ACsXcF5uKnQ4k+K9C7ANciRIgqQYSoEkSPhj4Y9GZuY8xjlBSxfBMTYKIhQlQJIkSVIEJUCSJElSBCVAkiRJUg/gkx2Zd9b5k3f0/zz1iSUVULMNEQPToAXagcaEQrk+4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzUrMDA6MDCGfIOnAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAw9yE7GwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Unit\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 1000 Head</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 100mg/An</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. tonnes</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12679</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12651</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12840</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">33.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAAAqCAQAAAB19uFeAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAbElEQVRIx2P8z0A9wERFswaxYSzInGlkBGAWIw7DGBjCSTRqJe28OWrYcDIMLZ2tJM8UKGBETvSMZBiArB/FZVNJzk7ZKPZTlJ3QA2XwxuaoYcPJsGGbN1FdMFrVjRo25AyjXd4cVN4cvIYBAKnqEO+spkjRAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAwhnyDpwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMPchOxsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Value\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 291341.2 (2232761)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 31996 &le; 76769955</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 91235.8 (7.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21325 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAhklEQVRo3u3aMQ6AIBBE0VnDHT2E59E7eEqtNEhDY9wh/t8RmpcAFRuH3JuyARC/qdSL7b6YS+Sy6hdSnluzJGnP9TUNcNAQIboEEaJLECG6BBGiSxAhugQRoksQIboEEaJLECG6BBGiSxAhugTxJ8Tmy/z6LF+zB0+qqYLItvQb4KAhvtEJ9tMIt4iCv54AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzUrMDA6MDCGfIOnAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM1KzAwOjAw9yE7GwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">40\n(0.1%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. *</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Fc</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Im</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. M</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1435</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3186</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10538</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">34.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13344</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">43.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2079</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAC0AAABOCAQAAAAec1flAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAtUlEQVRYw+2ZQQ6AIAwEwfBHHuF79A++Ui9qKEiJUEyKuzcvEzK2G4l2N70ydSMrRbvwYT3Fz7YWF7656NTeeA1CgAaaj6OPmyDahvtTvYR3mG3sJmRJyru+TRLXtEHazOscPqCHQOvskMKil5OvAnbRy+EE6pwQoIHm89MOiY+aFdJ23aA6dU4I0EDzGaxDWq4aj0KuDpEQo3NCgAaaj84OIUIEvkNyaNkADTTQr2LxN+kz9AFprCDPIpK3MAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMIZ8g6cAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDgtMzBUMjI6NDg6MzUrMDA6MDD3ITsbAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">7548\n(19.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag Description\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aggregate, may include of</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Calculated data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Data not available</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. FAO data based on imputat</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. FAO estimate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Official data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Unofficial figure</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3186</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13344</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">35.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">40</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2079</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">5.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">10538</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">27.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">7548</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">19.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1435</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.8%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACcAAABaCAQAAACRFoehAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCPp9aERAAAAxElEQVRYw+2YYQ5AMAyFTdzRIZyHOzglv7CNUt3IS/PeLyK+rO3e2iwsTU21VWnguC5+mZJEDkGHiH/q0k/9/jQjBEsccSpl29i2eQ+F2CJKV2USTTbaDr9oFaJntUrTg11Z4rzisD2bBGv0rIQrF3HEOcD902e1c3Guyz5rP6awS0GcVxx2nzXOxpKnTbOxnBLsyhLnFefIs8/d94VnNYnArixxMDhsk30Z7OZZ62R8Wl1vuIW6wZWKOK+4Lz0LFyw2bgVJ1yaUfcACugAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOC0zMFQyMjo0ODozNSswMDowMIZ8g6cAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDgtMzBUMjI6NDg6MzUrMDA6MDD3ITsbAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-08-31</p>\n</div>\n```\n:::\n\n```{.r .cell-code}\ndim(faostat_egg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 38170    14\n```\n:::\n:::\n\n\nThe `faostat_egg` dataset has 38170 rows and 13 columns. There are 40 missing values in the 'Values' column and 7548 missing values in 'Flag'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: data description 2\n\nprint(summarytools::dfSummary(faostat_livestock, varnumbers = FALSE, plain.ascii = FALSE, graph.magnif = 0.50, style = \"grid\", valid.col = FALSE), \n      method = 'render', table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>faostat_livestock</h4>\n<strong>Dimensions</strong>: 82116 x 14\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">Domain Code\n[character]</td>\n      <td align=\"left\">1. QA</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCR3kTSyAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM2KzAwOjAwt5SZOgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNiswMDowMMbJIYYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Domain\n[character]</td>\n      <td align=\"left\">1. Live Animals</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCR3kTSyAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM2KzAwOjAwt5SZOgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNiswMDowMMbJIYYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 912.7 (1855)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 146 &le; 5504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 148 (2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">253 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCR3kTSyAAAAnElEQVRo3u3awQmAMBAFUVfSoz1oPaYHq9SL4EbMKeL+4MxFRJAHJrmstg/qjdEAiN+U/E12C3OxSJbfIal8NJ3XLdJ3q4MPDRGiShAhqgQRokoQIaoEEaJKECGqBBGiShAhqgQRokoQf0JM7a9oaS0Guc8Ts2DiNS+rT8w6+NAQIaoUvqN97ghyx4/5gynL/G4y14iadbAWIb7RASWQDhAnlEI7AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM2KzAwOjAwt5SZOgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNiswMDowMMbJIYYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Area\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. China, mainland</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Eastern Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Eastern Asia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Eastern Europe</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Egypt</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Europe</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. India</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Northern Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 243 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">522</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">76896</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">93.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFIAAACJCAQAAAAV3Kf8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCR3kTSyAAAA9klEQVR42u3VQQrCQBAFUUdyx5zMQ+SUceOiR3AjrVOfVLkSQR5p8Y/zxu++GiDyr53l9QD9QKsr4kmKFElLpEhaEchRl3Cs1pSqa3qSpO2uRZxbpEhaIkXSikC63V1FnFukSFoiRdKKQLrdXUWcW6RIWiJF0opAut1dRZxbpEhaIkXSyptFam63SFoiRdIS2VXedjuLIgGJFElL5KWQbndXEecWKZKWSJG0IpBud1cR5xYpkpZIkbQikG53VxHnFimSlkiRtCKQEdu91Q9Q212e2DZ/sq+mvTqmdxG/SZEiaYns6u1/8vjuW37cII3MpyLOLbKrJ/NsNfnFXzIGAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM2KzAwOjAwt5SZOgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNiswMDowMMbJIYYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element Code\n[numeric]</td>\n      <td align=\"left\">1 distinct value</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">5111</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCR3kTSyAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM2KzAwOjAwt5SZOgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNiswMDowMMbJIYYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Element\n[character]</td>\n      <td align=\"left\">1. Stocks</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCR3kTSyAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM2KzAwOjAwt5SZOgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNiswMDowMMbJIYYAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1017.7 (83.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">866 &le; 1034 &le; 1126</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 120 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">866</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">13086</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">15.9%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">946</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3505</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">976</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">11919</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">14.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1016</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12498</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">15.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1034</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">12015</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">14.6%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1096</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">11104</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">13.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1107</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">8571</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1110</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">6153</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">7.5%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1126</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3265</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABkAAABxCAQAAACKR8DfAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCUAlgQkAAAAs0lEQVRYw+2YwQ2AIAwAqXFHdtB5cAem1I8PLBRBIhRof0YutuXSgHCq3FiyiUrI6j4cZGEbEIhSOgjYPsqfHEFbaRMQcB0Bcpm76vEVc7/ZadavRROWFZYvSG7UEaY0MUPMsadzCXMM18d2X0ZCGg4lHCLMoIg4JsjfCBvH8FHr1TE/VbZNnhxh4VjoKB91LJwm2yZPjjR2jL4oEo7FEmTb5JGQvi6J8iOiR6TUMU61fEAun9AzTjBzN50AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzcrMDA6MDAR45KOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM3KzAwOjAwYL4qMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Item\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Asses</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Buffaloes</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Camels</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Cattle</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Goats</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Horses</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Mules</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Pigs</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Sheep</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">8571</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">10.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3505</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">3265</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">13086</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12498</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11104</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">13.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">6153</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">7.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12015</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11919</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABkAAABxCAQAAACKR8DfAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCUAlgQkAAAAs0lEQVRYw+2XUQ6AIAhAtXVHD+F56g6e0j7qI1FKsykM+GmuXgN6w7TRtMbSTAxC1vtizwrz9rxGDDHGJavAq3zhCPiUoQKxdxUs+hgqzHbd8Tib1+KAZT+Vr0hrjBGmNzF1jDMycSiVXo0mVtYlTZdsk4UjhBxLh1SFYzBZsk0WjpBxDG6Dr47lqZJtsnBksmP4Dxbi2FOCZJssHCEzx3Sv5IHwOiTCUMc4IL2OUarlA3IAczQz4+EM47YAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzcrMDA6MDAR45KOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM3KzAwOjAwYL4qMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.4 (16.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCUAlgQkAAAAuUlEQVRo3u3aWw5EQBCFYS32aA9jPWMPVsmLmHpgoiiciv+8aAndX9LVSbuUsVJP/TQA4j1p7EkJ7vzrLPRuAdgbG18nXlY7H4el9a+9nnBitWNQXxLUYgJiyER7l8UJ4vGhoutvk+hdgb+rr0yCWoQIUSUQIaoE4kuIF+y6j8fstMxjlBRxfeeUYKIhQlQJRIgqgQhRJRAhqgQiRJVAhKgSiC8hFvvZr5f53eRj3owVGdVmEkw0xIhMxGIa0nWvQqkAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzcrMDA6MDAR45KOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM3KzAwOjAwYL4qMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 1990.4 (16.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1961 &le; 1991 &le; 2018</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 29 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCUAlgQkAAAAuUlEQVRo3u3aWw5EQBCFYS32aA9jPWMPVsmLmHpgoiiciv+8aAndX9LVSbuUsVJP/TQA4j1p7EkJ7vzrLPRuAdgbG18nXlY7H4el9a+9nnBitWNQXxLUYgJiyER7l8UJ4vGhoutvk+hdgb+rr0yCWoQIUSUQIaoE4kuIF+y6j8fstMxjlBRxfeeUYKIhQlQJRIgqgQhRJRAhqgQiRJVAhKgSiC8hFvvZr5f53eRj3owVGdVmEkw0xIhMxGIa0nWvQqkAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzcrMDA6MDAR45KOAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM3KzAwOjAwYL4qMgAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Unit\n[character]</td>\n      <td align=\"left\">1. Head</td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">82116</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">100.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFcAAAASCAQAAACEVIo4AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCUAlgQkAAAASElEQVRIx2P8zzCUANNAO2DUuYMHsCBzpv0PH2j3YICVDFmMCN4QC91R5446d9S5o84d8s5lQeWuHGj3EACMoy2yUecOUecCACFaBc64QinoAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM3KzAwOjAwEeOSjgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozNyswMDowMGC+KjIAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Value\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 11625569 (64779790)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 224667 &le; 1489744504</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2364200 (5.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">43667 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAAhElEQVRo3u3asQ2AIBBA0cOwo0M4D+7glNoZFEvjfZP/O7F5EayOsge9KRsg8Ztq/7CeB3Mpuaz+D6nXV3NERGy5vls/2GiJEilJlEhJokRKEiVSkiiRkkSJlCRKpCRRIiWJEilJlEhJokRKEt+oPi83zPB8II7D8pZzBaX7MMVLMBIhHV/vCrkqeD4EAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM4KzAwOjAw56viZwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozOCswMDowMJb2WtsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">1301\n(1.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. *</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. A</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. F</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Im</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. M</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2667</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12567</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">28.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24550</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">56.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">6.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1185</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.7%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADYAAABCCAQAAAC2/+2BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAAs0lEQVRYw+2XwQ2AIAxFi2FHh3Ae3cEp9UCihQAiUiTN/zfi4aW0PNAc1C9TR5ZimOWL7WrgYloB+ExY/9NMRES7UGV6ewYYYOPAgkMtdZxdDNdJM0exJHW1vrjcauwZdeNz6rZb7zQCBtg4MLjxQzkJWLkbS+O3Re80AgZYNnp19d82cje2+6tOwG43yvRO7+gDBlg2et0Y0ZWEqFyCnrV+ymVhsgEMMMCIurqxc2WA1eUE4IIczKGDndUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDgtMzBUMjI6NDg6MzgrMDA6MDDnq+JnAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA4LTMwVDIyOjQ4OjM4KzAwOjAwlvZa2wAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">38270\n(46.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Flag Description\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Aggregate, may include of</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Data not available</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. FAO data based on imputat</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. FAO estimate</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Official data</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Unofficial figure</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">12567</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">15.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1185</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">1.4%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2877</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">24550</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">29.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">38270</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">46.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">2667</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAC8AAABOCAQAAAAahofYAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAAuElEQVRYw+2XSw6AIAxExXBHDuF58A6eEhduCimmfGosmdkRzEtTh0nr0qapXZVuHO/p4az8iMO1ICnE51eB+fwaqN5274FfFl/4fsTjnBx9Y02PsypK/LL3McXJ8W/bOcAD/0u8cuZkiflEQtvY8a6iOaGPIsXPFvDAW8Abm3OYzJFKkk2C5YeXrI1LOQd44IWyvVsNZE695Ap+xpyTt9e2c4AHvk/LZQ52K+CBt4RXzRz16oGnugEo8iFdqb5dnQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOC0zMFQyMjo0ODozOCswMDowMOer4mcAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDgtMzBUMjI6NDg6MzgrMDA6MDCW9lrbAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-08-31</p>\n</div>\n```\n:::\n\n```{.r .cell-code}\ndim(faostat_livestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 82116    14\n```\n:::\n:::\n\n\nThere are 82116 rows and 13 columns in the `faostat_livestock` dataset. It has missing values too (1301 in 'Value' and 38270 in 'Flag').\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: data description 3\n\nprint(summarytools::dfSummary(faostat_country, varnumbers = FALSE, plain.ascii = FALSE, graph.magnif = 0.50, style = \"grid\", valid.col = FALSE), \n      method = 'render', table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>faostat_country</h4>\n<strong>Dimensions</strong>: 1943 x 7\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">Country Group Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5501.8 (1356.5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">336 &le; 5403 &le; 9011</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 648 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">58 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAAr0lEQVRo3u2awQ2AIBAExdCjPWg92oNV6vcg0QdZdElmXvK5DBznZ0nX5M78twCK35DjIgkK7tXl3pqKxiK5pcA7S/g+BfUGaDSKKLqAIoouoIiiCyii6AKKKLqAIoouoIiiCyii6AKKKLqAogJB7rJ3Tjol0ZA6DCoZoNEoKugQU7ZRDV3IX20U49CVI1coljtpS5L1VKf4tJM/SfHgDpvnJmvoYLKxemSAnw6KCm6KWhGqICaMAAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOC0zMFQyMjo0ODozOCswMDowMOer4mcAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDgtMzBUMjI6NDg6MzgrMDA6MDCW9lrbAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Country Group\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. World</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Non-Annex I countries</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Net Food Importing Develo</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Annex I countries</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. High-income economies</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Africa</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Europe</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Americas</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Small Island Developing S</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Upper-middle-income econo</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 48 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">277</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">161</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">8.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">81</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">78</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">4.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">64</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">63</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">63</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.2%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">61</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.1%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">58</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">3.0%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">56</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">2.9%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">981</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">50.5%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADIAAACJCAQAAADEO6OMAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAA4UlEQVRo3u2aSQ6EIBAAwfhHHzHv0T/4ypnDXECBRNJNmrbqZjSWslQ8GL9Bn2WAw5FkTQ+O4gR9Ys+N01ut+antdvEp8CZ+5gQJEj0um1Fi692J6fbv6keFalb2rF19zSpRbZfkwPlZXUiQ6OG8XXLV+nOZk63w5SUu0QEJkskltOsRtAsJEiMS1+2SLlehXRr4WV1IkIQwdVbGV5h2IUFiRjJxu8gKEiQvltCuNrQLCRKbEtrVhnYhQWJTQrva0C4kSGxKfLVL6vErErl25cPudnUheYtk/J8FWviZkyGSHw9IO186YaebAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM4KzAwOjAw56viZwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozOCswMDowMJb2WtsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Country Code\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 142.2 (96.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 136 &le; 622</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 133 (0.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">277 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7CAQAAACp6a6BAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAA0ElEQVRo3u2aQQ6DIBBFncY7eof2PPYOPaXdNGU0EjQZ4JO8t1ETFg9mRghg26TOo7cAim2Y/YedNFhdsr5saoSvkLncfPk9P638DgwQ6AEULwQ60Scvd4olheX/1jIvD6N4vTRSd2qPZzbQa2FmbFfnWcXev5rEABWNIooqoIiiCiiiqAKKKKqAIooqoIiiCrd2xs6pvbsToFh7a2WAQKOIogoooqgCihEEzNFR7E563IJESDG3IKmkGHmgaX503zLXTZ6uWyZjlWWAikYxgi87hByy+wEpdgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOC0zMFQyMjo0ODozOCswMDowMOer4mcAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDgtMzBUMjI6NDg6MzgrMDA6MDCW9lrbAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">Country\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Afghanistan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Burkina Faso</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. Burundi</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Central African Republic</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Chad</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Comoros</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Ethiopia</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. Guinea-Bissau</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. Lesotho</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. Malawi</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 267 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1833</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFMAAACJCAQAAAD6HszCAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCaZn1WeAAAA9klEQVR42u3VQQrCQBAFUUdyR0/mIXLKZCc9ghvpMPVJlSsR5JEW/zgeCT1XA2Qu6CivN+qHWmUhT1OmTGoyZVILYY66j2O1ZqrKpqfJ2vRayNFlyqQmUya1EKab3lnI0WXKpCZTJrUQppveWcjRZcqkJlMmtRCmm95ZyNFlyqQmUya1xLHk5qbLpCZTJjWZnSVuumMpE5RMmdRk3pDppncWcnSZMqnJlEkthOmmdxZydJkyqcmUSS2E6aZ3FnJ0mTKpyZRJLYQZsulb/QC26eWpbfMnr9W0T/v0LuS3KVMmNZmdff1v7v99y+UN1vD8KuToMjs7Aa8JNflzKItPAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM4KzAwOjAw56viZwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozOCswMDowMJb2WtsAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">M49 Code\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. 004</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. 108</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. 140</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. 148</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. 174</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. 231</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. 426</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. 454</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. 466</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. 496</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 267 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1833</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFMAAACJCAQAAAD6HszCAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCfumGUIAAAA9klEQVR42u3VQQrCQBAFUUdyR0/mIXLKZCc9ghvpMPVJlSsR5JEW/zgeCT1XA2Qu6CivN+qHWmUhT1OmTGoyZVILYY66j2O1ZqrKpqfJ2vRayNFlyqQmUya1EKab3lnI0WXKpCZTJrUQppveWcjRZcqkJlMmtRCmm95ZyNFlyqQmUya1xLHk5qbLpCZTJjWZnSVuumMpE5RMmdRk3pDppncWcnSZMqnJlEkthOmmdxZydJkyqcmUSS2E6aZ3FnJ0mTKpyZRJLYQZsulb/QC26eWpbfMnr9W0T/v0LuS3KVMmNZmdff1v7v99y+UN1vD8KuToMjs7Aa8JNflzKItPAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM5KzAwOjAwQdzp0wAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozOSswMDowMDCBUW8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">ISO2 Code\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. AF</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. BF</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. BI</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. CF</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. ET</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. GW</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. KM</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. LS</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. ML</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. MN</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 266 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1825</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFMAAACJCAQAAAD6HszCAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCfumGUIAAAA9klEQVR42u3VQQrCQBAFUUdyR0/mIXLKZCc9ghvpMPVJlSsR5JEW/zgeCT1XA2Qu6CivN+qHWmUhT1OmTGoyZVILYY66j2O1ZqrKpqfJ2vRayNFlyqQmUya1EKab3lnI0WXKpCZTJrUQppveWcjRZcqkJlMmtRCmm95ZyNFlyqQmUya1xLHk5qbLpCZTJjWZnSVuumMpE5RMmdRk3pDppncWcnSZMqnJlEkthOmmdxZydJkyqcmUSS2E6aZ3FnJ0mTKpyZRJLYQZsulb/QC26eWpbfMnr9W0T/v0LuS3KVMmNZmdff1v7v99y+UN1vD8KuToMjs7Aa8JNflzKItPAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM5KzAwOjAwQdzp0wAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozOSswMDowMDCBUW8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">8\n(0.4%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">ISO3 Code\n[character]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. AFG</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. BDI</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. BFA</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. CAF</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. COM</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. ETH</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. GNB</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">8. LSO</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">9. MLI</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10. MNG</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">[ 267 others ]</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">11</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">0.6%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">1833</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">94.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFMAAACJCAQAAAD6HszCAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmCB4WMCfumGUIAAAA9klEQVR42u3VQQrCQBAFUUdyR0/mIXLKZCc9ghvpMPVJlSsR5JEW/zgeCT1XA2Qu6CivN+qHWmUhT1OmTGoyZVILYY66j2O1ZqrKpqfJ2vRayNFlyqQmUya1EKab3lnI0WXKpCZTJrUQppveWcjRZcqkJlMmtRCmm95ZyNFlyqQmUya1xLHk5qbLpCZTJjWZnSVuumMpE5RMmdRk3pDppncWcnSZMqnJlEkthOmmdxZydJkyqcmUSS2E6aZ3FnJ0mTKpyZRJLYQZsulb/QC26eWpbfMnr9W0T/v0LuS3KVMmNZmdff1v7v99y+UN1vD8KuToMjs7Aa8JNflzKItPAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTMwVDIyOjQ4OjM5KzAwOjAwQdzp0wAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0zMFQyMjo0ODozOSswMDowMDCBUW8AAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-08-31</p>\n</div>\n```\n:::\n\n```{.r .cell-code}\ndim(faostat_country)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1943    7\n```\n:::\n:::\n\n\nThe `faostat_country` dataset has 1943 rows and 7 columns. It contains information on each country name and unique code, the country groups they belong to, as well as codes for 'M49', 'ISO2', and 'ISO3'. Only the 'ISO2' column has 8 missing values.\n\n## Tidy Data\n\n### Tidying `faostat_country`\n\n`faostat_country` seems tidy enough to work with.\n\n### Tidying `faostat_egg`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# turning 'Element' and 'Flag Description' into factor type\n\nfaostat_egg$Element <- as.factor(faostat_egg$Element)\nfaostat_egg$'Flag Description' <- as.factor(faostat_egg$'Flag Description')\n\n\n# deleting 'Year Code'\n\nfaostat_egg <- faostat_egg %>%\n  select(-'Year Code')\n```\n:::\n\n\n### Tidying `faostat_livestock`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# turning 'Element' and 'Flag Description' into factor type\nfaostat_livestock$Element <- as.factor(faostat_livestock$Element)\nfaostat_livestock$'Flag Description' <- as.factor(faostat_livestock$'Flag Description')\n\n\n# deleting 'Year Code'\nfaostat_livestock <- faostat_livestock %>%\n  select(-'Year Code')\n```\n:::\n\n\n\n### Tidying `faostat_cattle`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# turning 'Element' and 'Flag Description' into factor type\n\nfaostat_cattle$Element <- as.factor(faostat_cattle$Element)\nfaostat_cattle$'Flag Description' <- as.factor(faostat_cattle$'Flag Description')\n\n\n# deleting 'Year Code'\n\nfaostat_cattle <- faostat_cattle %>%\n  select(-'Year Code')\n```\n:::\n\n\n## Join Data\n\nBe sure to include a sanity check, and double-check that case count is correct!\n\nJoining `faostat_egg` and `faostat_livestock` by rowbinding:\n\n\n::: {.cell}\n\n```{.r .cell-code}\negg_livestock <- bind_rows(faostat_egg,faostat_livestock)\n\ndim(egg_livestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 120286     13\n```\n:::\n:::\n\n\nBoth datasets had 13 columns and the combined number of rows in the new dataset is $$38170 + 82116 = 120286$$.\n\nJoining `faostat_cattle` and `faostat_livestock`by rowbinding:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncattle_livestock <- bind_rows(faostat_cattle,faostat_livestock)\n\ndim(cattle_livestock)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 118565     13\n```\n:::\n:::\n\n\nBoth datasets had 13 columns and the combined number of rows in the new dataset is $$36449 + 82116 = 118565$$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#figuring out the primary key for 'faostat_country'\nfaostat_country %>% \n  count('Country Code') %>% \n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `\"Country Code\"`     n\n  <chr>            <int>\n1 Country Code      1943\n```\n:::\n\n```{.r .cell-code}\nfaostat_country\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,943 × 7\n   `Country Group Code` `Country Group` Countr…¹ Country M49 C…² ISO2 …³ ISO3 …⁴\n                  <dbl> <chr>              <dbl> <chr>   <chr>   <chr>   <chr>  \n 1                 5100 Africa                 4 Algeria 012     DZ      DZA    \n 2                 5100 Africa                 7 Angola  024     AO      AGO    \n 3                 5100 Africa                53 Benin   204     BJ      BEN    \n 4                 5100 Africa                20 Botswa… 072     BW      BWA    \n 5                 5100 Africa               233 Burkin… 854     BF      BFA    \n 6                 5100 Africa                29 Burundi 108     BI      BDI    \n 7                 5100 Africa                35 Cabo V… 132     CV      CPV    \n 8                 5100 Africa                32 Camero… 120     CM      CMR    \n 9                 5100 Africa                37 Centra… 140     CF      CAF    \n10                 5100 Africa                39 Chad    148     TD      TCD    \n# … with 1,933 more rows, and abbreviated variable names ¹​`Country Code`,\n#   ²​`M49 Code`, ³​`ISO2 Code`, ⁴​`ISO3 Code`\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\negg_livestock %>% \n  count('Area Code') %>% \n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  `\"Area Code\"`      n\n  <chr>          <int>\n1 Area Code     120286\n```\n:::\n\n```{.r .cell-code}\nunique(faostat_country$`Country Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1]   4   7  53  20 233  29  35  32  37  39  24  45  46 107 250  72  59  61\n [19] 178 209 238  62  71  74  75  81  90 175 114 122 123 124 129 130 133 136\n [37] 137 270 143 144 147 158 159 182 184 187 193 195 196 197 201 202 277 276\n [55] 206 217 222 226 215 616 205 251 181 258   8   9  22  12  14  23  17  19\n [73] 278  31  21 239  33 609  36  40  44  48  49 279  55  56  58  60  65  69\n [91]  85  86  87  89  91  93  95 109 135 138 142 151 157 622 166 169 170 177\n[109] 282 188 189 190 191 281 280 614 271 207 220 224 231 240 234 236   5  10\n[127]  11  57 255  15  27 259  98  50 167  51  54  63  64  67  68  70  79  82\n[145]  84  88  97  99 104 264 106 110 119 125 126 256 134 140 150 153 156 161\n[163] 163 162 172 173 174 183 185 199 198 203 260 210 211 218 223 230 229 228\n[181] 243  30   2   1  52  13  16  18  26 115 351  96 128  41 214 116  73 100\n[199] 101 102 103 105 112 108 118 113 120 121 131 132 141  28 149 221 165 299\n[217] 171 179 117 194 200  38 212 208 216 176 213 225 235 237 249 246 247  42\n[235]  43  92 146 284   3   6  80  78  77 274  94 283 275 273 154 619 192 272\n[253] 186 620 621 248 180  83  25 227 155 145 168  66 127 617 148 164 232  47\n[271] 160 244 219 111 139 618 242\n```\n:::\n\n```{.r .cell-code}\nunique(egg_livestock$`Area Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1]    2    3    4    5    7    8    9    1   10   11   52   12   13   16   14\n [16]   57  255   15   23   53   17   18   19   80   20   21   26   27  233   29\n [31]   35  115   32   33   36   37   39   40   96  128   41  214   44   45   46\n [46]   47   48  107   98   49   50  167   51  116  250   54   55   56   58   59\n [61]   60   61  178   63  209  238   62   66   67   68   69   70   74   75   73\n [76]   79   81   84   86   87   88   89   90  175   91   93   95   97   99  100\n [91]  101  102  103  104  105  106  109  110  112  108  114   83  118  113  120\n[106]  119  121  122  123  124  125  126  256  129  130  131  133  134  135  136\n[121]  137  138  145  141  273  142  143  144   28  147  148  149  150  151  153\n[136]  156  157  158  159  160  154  162  221  164  165  299  166  168  169  170\n[151]  171  173  174  177  179  117  146  182  183  185  184  188  189  190  191\n[166]  244  193  194  195  272  186  196  197  200  199  198   25  201  202  277\n[181]  203   38  276  206  207  210  211  212  208  216  176  217  218  219  220\n[196]  222  223  213  227  226  230  225  229  215  231  240  234  228  235  155\n[211]  236  237  243  249  248  251  181 5000 5100 5101 5102 5103 5104 5105 5200\n[226] 5203 5204 5206 5207 5300 5301 5302 5303 5304 5305 5400 5401 5402 5403 5404\n[241] 5500 5501 5502 5503 5504   22  239   72   65   64   85  161  187  205\n```\n:::\n:::\n\n\nSo 'Country Code' can be used as the primary key for the `faostat_country` dataset to connect to the `egg_livestock` dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoin_anti <- egg_livestock %>%\n  anti_join(faostat_country, by = c(\"Area Code\"=\"Country Code\")) \n\ndim(join_anti)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17346    13\n```\n:::\n\n```{.r .cell-code}\nunique(join_anti$`Area Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 5000 5100 5101 5102 5103 5104 5105 5200 5203 5204 5206 5207 5300 5301 5302\n[16] 5303 5304 5305 5400 5401 5402 5403 5404 5500 5501 5502 5503 5504\n```\n:::\n\n```{.r .cell-code}\nunique(egg_livestock$`Area Code`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1]    2    3    4    5    7    8    9    1   10   11   52   12   13   16   14\n [16]   57  255   15   23   53   17   18   19   80   20   21   26   27  233   29\n [31]   35  115   32   33   36   37   39   40   96  128   41  214   44   45   46\n [46]   47   48  107   98   49   50  167   51  116  250   54   55   56   58   59\n [61]   60   61  178   63  209  238   62   66   67   68   69   70   74   75   73\n [76]   79   81   84   86   87   88   89   90  175   91   93   95   97   99  100\n [91]  101  102  103  104  105  106  109  110  112  108  114   83  118  113  120\n[106]  119  121  122  123  124  125  126  256  129  130  131  133  134  135  136\n[121]  137  138  145  141  273  142  143  144   28  147  148  149  150  151  153\n[136]  156  157  158  159  160  154  162  221  164  165  299  166  168  169  170\n[151]  171  173  174  177  179  117  146  182  183  185  184  188  189  190  191\n[166]  244  193  194  195  272  186  196  197  200  199  198   25  201  202  277\n[181]  203   38  276  206  207  210  211  212  208  216  176  217  218  219  220\n[196]  222  223  213  227  226  230  225  229  215  231  240  234  228  235  155\n[211]  236  237  243  249  248  251  181 5000 5100 5101 5102 5103 5104 5105 5200\n[226] 5203 5204 5206 5207 5300 5301 5302 5303 5304 5305 5400 5401 5402 5403 5404\n[241] 5500 5501 5502 5503 5504   22  239   72   65   64   85  161  187  205\n```\n:::\n\n```{.r .cell-code}\ncheck1 <- join_anti %>% \n  select(`Area Code`,`Area`) %>% \n  group_by(`Area Code`,`Area`) %>% \n  tally()\ncheck1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 28 × 3\n# Groups:   Area Code [28]\n   `Area Code` Area                 n\n         <dbl> <chr>            <int>\n 1        5000 World              696\n 2        5100 Africa             696\n 3        5101 Eastern Africa     696\n 4        5102 Middle Africa      638\n 5        5103 Northern Africa    696\n 6        5104 Southern Africa    638\n 7        5105 Western Africa     638\n 8        5200 Americas           638\n 9        5203 Northern America   580\n10        5204 Central America    580\n# … with 18 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nThe anti_join() on `egg_livestock` and `faostat_country` reveals that there are 17346 observations in `egg_livestock` that did not find a match in `faostat_country`. `join_anti` has 13 columns, the same as the `egg_livestock` dataset.\n\n\n## Analyze Data\n\nI'm looking to compare egg production to camel livestock production in Bahrain and Qatar using a line graph with facet wrap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\negg_livestock_filt <- egg_livestock %>%\n  select(Year,Area,Item,Element,Value) %>%\n  filter(Area==\"Bahrain\"|Area==\"Qatar\") %>%\n  filter(Element==\"Production\"| Item==\"Camels\")\negg_livestock_filt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 216 × 5\n    Year Area    Item                Element    Value\n   <dbl> <chr>   <chr>               <fct>      <dbl>\n 1  1961 Bahrain Eggs, hen, in shell Production    60\n 2  1962 Bahrain Eggs, hen, in shell Production    60\n 3  1963 Bahrain Eggs, hen, in shell Production    60\n 4  1964 Bahrain Eggs, hen, in shell Production    60\n 5  1965 Bahrain Eggs, hen, in shell Production    70\n 6  1966 Bahrain Eggs, hen, in shell Production    70\n 7  1967 Bahrain Eggs, hen, in shell Production    80\n 8  1968 Bahrain Eggs, hen, in shell Production    80\n 9  1969 Bahrain Eggs, hen, in shell Production    80\n10  1970 Bahrain Eggs, hen, in shell Production    80\n# … with 206 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\negg_livestock_filt %>%\n  ggplot(aes(x=Year, y=Value, color=Area)) +\n    geom_line() + labs(title = \"Egg Production versus Camel Stocks (1961-2018)\", x = \"Year\", y = \"Value\") + facet_wrap(~ Element) + theme_minimal()\n```\n\n::: {.cell-output-display}\n![](challenge8_AnanyaPujary_files/figure-html/analyze data 2-1.png){width=672}\n:::\n:::\n\nOver time, egg production in Qatar exceeded that in Bahrain. Camel livestock production in Qatar evidently far-exceeds stocks in Bahrain too.\n",
    "supporting": [
      "challenge8_AnanyaPujary_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}