{
  "hash": "fb6038bbbc2cca03e99ca9f3429f2479",
  "result": {
    "markdown": "---\ntitle: \"Homework 3\"\nauthor: \"Young Soo Choi\"\ndesription: \"Read and descrive the data\"\ndate: \"08/28/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw3\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read and tidy the Data\n\nUse debt data following homework 2. After creating a date column in the imported data, I tidied the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndebt_raw <- read_xlsx(\"_data/debt_in_trillions.xlsx\")\n\ndebt<-debt_raw%>%\n  mutate(date = parse_date_time(`Year and Quarter`, \n                           orders=\"yq\"))\n\ntidy_debt<-debt%>%\n  pivot_longer(Mortgage:Total, names_to = 'types', values_to = 'debts')\n\ntidy_debt<-tidy_debt%>%\n  select(-'Year and Quarter')\n\ntidy_debt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 518 × 3\n   date                types        debts\n   <dttm>              <chr>        <dbl>\n 1 2003-01-01 00:00:00 Mortgage     4.94 \n 2 2003-01-01 00:00:00 HE Revolving 0.242\n 3 2003-01-01 00:00:00 Auto Loan    0.641\n 4 2003-01-01 00:00:00 Credit Card  0.688\n 5 2003-01-01 00:00:00 Student Loan 0.241\n 6 2003-01-01 00:00:00 Other        0.478\n 7 2003-01-01 00:00:00 Total        7.23 \n 8 2003-04-01 00:00:00 Mortgage     5.08 \n 9 2003-04-01 00:00:00 HE Revolving 0.26 \n10 2003-04-01 00:00:00 Auto Loan    0.622\n# … with 508 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\n## Descriptive Statistics\n\nUsing functions group_by and summarise, the average value and standard deviation of the total amount of debt and the amount of debt by type from the first quarter of 2003 to the second quarter of 2021 were calculated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nds_debt<-tidy_debt%>%\n  group_by(types)%>%\n  summarise(mean=mean(debts),\n            sd=sd(debts))\nds_debt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 3\n  types          mean     sd\n  <chr>         <dbl>  <dbl>\n1 Auto Loan     0.931 0.235 \n2 Credit Card   0.757 0.0688\n3 HE Revolving  0.516 0.124 \n4 Mortgage      8.27  1.18  \n5 Other         0.383 0.0458\n6 Student Loan  0.919 0.428 \n7 Total        11.8   1.74  \n```\n:::\n:::\n\nIn order to find out the proportion of each type of debt, the proportion and the percentage column were added using the mutate function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npro_debt<-ds_debt%>%\n  mutate(pro=round(mean/11.7793751,5), percent=pro*100)\npro_debt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 7 × 5\n  types          mean     sd    pro percent\n  <chr>         <dbl>  <dbl>  <dbl>   <dbl>\n1 Auto Loan     0.931 0.235  0.0790    7.90\n2 Credit Card   0.757 0.0688 0.0642    6.42\n3 HE Revolving  0.516 0.124  0.0438    4.38\n4 Mortgage      8.27  1.18   0.702    70.2 \n5 Other         0.383 0.0458 0.0325    3.25\n6 Student Loan  0.919 0.428  0.0780    7.80\n7 Total        11.8   1.74   1       100   \n```\n:::\n:::\n\nLooking at the average data for 18 years, it can be seen that the proportion of mortgage is the largest among the total debt. 'Mortgage' accounts for about 70.2% of the total, followed by 'Auto Loan' with 7.9% and 'Student Loan' with 7.8%.\n\nIn the case of volatility, it can be identified using the standard deviation, and the standard deviation of 'Mortgage' was the highest at 1.18, and the next largest change was 'Student Loan', and the standard deviation was 0.42.\n\n## Visualization\n\nBased on the above data, I drew the total amount and proportion of debt by debt type on a bar graph, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npro_debt %>% filter(types!='Total')%>%\n  ggplot(aes(x=types, y=mean)) +\n  geom_bar(stat = 'identity')+\n  geom_text(aes(label=round(mean,5)), vjust=-0.3)\n```\n\n::: {.cell-output-display}\n![](homework3-youngsoo-choi_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npro_debt %>% filter(types!='Total')%>%\n  ggplot(aes(x=types, y=percent)) +\n  geom_bar(stat = 'identity')+\n  geom_text(aes(label=round(percent,5)), vjust=-0.3)\n```\n\n::: {.cell-output-display}\n![](homework3-youngsoo-choi_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nHowever, looking at the graph, it is difficult to see how the proportion of each type of debt has changed year by year. \n\nIn the final report, I'll expand the scope of the analysis. And for effective visualization, I will add titles, categories, etc. to the graph and use colors to complement the graph to make it easier to recognize.\n\n\n\n",
    "supporting": [
      "homework3-youngsoo-choi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}