{
  "hash": "70cad481f8f20c66e773ed0d6fad21f6",
  "result": {
    "markdown": "---\ntitle: \"Challenge 3\"\nauthor: \"Mani Shanker Kamarapu\"\ndesription: \"Tidy Data: Pivoting\"\ndate: \"08/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_3\n  - Australian_marriage_law\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvote_response <- read_excel(\"_data/australian_marriage_law_postal_survey_2017_-_response_final.xls\", sheet = \"Table 2\", skip = 7, col_names = c(\"Area\", \"Yes\", \"Yes_P\", \"No\", \"No_P\", \"Totalclear\", \"Totalclear_P\", \"Empty\", \"clear\", \"clear_P\", \"Not_Eligible\", \"Not_Eligible_P\", \"NoResponse\", \"NoResponse_P\", \"Total\", \"Total_P\")) %>%\n  select(\"Area\", \"Yes\", \"No\", \"Not_Eligible\", \"NoResponse\", \"Total\") %>%\n  drop_na(\"Area\") %>%\n  filter(!grepl(\"Total\", Area))\nR <- nrow(vote_response)-7\nvote_response <- slice(vote_response, 1:R)\nvote_response\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 158 × 6\n   Area                        Yes    No Not_Eligible NoResponse  Total\n   <chr>                     <dbl> <dbl>        <dbl>      <dbl>  <dbl>\n 1 New South Wales Divisions    NA    NA           NA         NA     NA\n 2 Banks                     37736 46343          247      20928 105254\n 3 Barton                    37153 47984          226      24008 109371\n 4 Bennelong                 42943 43215          244      19973 106375\n 5 Berowra                   48471 40369          212      16038 105090\n 6 Blaxland                  20406 57926          220      25883 104435\n 7 Bradfield                 53681 34927          202      17261 106071\n 8 Calare                    54091 35779          285      25342 115497\n 9 Chifley                   32871 46702          263      28180 108016\n10 Cook                      47505 38804          229      18713 105251\n# … with 148 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(vote_response)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 158   6\n```\n:::\n:::\n\n\nThe dimensions of the data set are `158` rows and `6` columns.\n\nThe data is on the postal survey of Australian Electoral Roll. It contains the data of the eligible participants and responses of the participants in federal election as at 24 August 2017. It has data based on different federal electoral divisions survey by the Australian Election Commission. It is basically the total number of response we got in each division during the federal election. The data set is untidy and variables are not defined correctly and there are a lot of extra variables which are not required and a bunch of NA values. So using different R functions to remove unwanted variables and drop some NA values and also remove extra rows.\n\n## Separating different divisions and areas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvote_response <- vote_response %>%\n  mutate(Division = case_when(\n    str_ends(Area, \"Divisions\") ~ Area,\n    TRUE ~ NA_character_ )) %>%\n  fill(Division) %>%\n  drop_na(\"Yes\")\nvote_response\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 150 × 7\n   Area        Yes    No Not_Eligible NoResponse  Total Division                \n   <chr>     <dbl> <dbl>        <dbl>      <dbl>  <dbl> <chr>                   \n 1 Banks     37736 46343          247      20928 105254 New South Wales Divisio…\n 2 Barton    37153 47984          226      24008 109371 New South Wales Divisio…\n 3 Bennelong 42943 43215          244      19973 106375 New South Wales Divisio…\n 4 Berowra   48471 40369          212      16038 105090 New South Wales Divisio…\n 5 Blaxland  20406 57926          220      25883 104435 New South Wales Divisio…\n 6 Bradfield 53681 34927          202      17261 106071 New South Wales Divisio…\n 7 Calare    54091 35779          285      25342 115497 New South Wales Divisio…\n 8 Chifley   32871 46702          263      28180 108016 New South Wales Divisio…\n 9 Cook      47505 38804          229      18713 105251 New South Wales Divisio…\n10 Cowper    57493 38317          315      25197 121322 New South Wales Divisio…\n# … with 140 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(vote_response)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 150   7\n```\n:::\n:::\n\n\nAfter we read the data and did some hard coding along with read, now we have separated the divisions row from the area column and formed a new column so we can use it as a grouping variable. \n\n## Using Pivot to tidy data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvote_response <- pivot_longer(vote_response, Yes:Total, names_to = \"Response\", values_to = \"Count\")\nvote_response\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 750 × 4\n   Area   Division                  Response      Count\n   <chr>  <chr>                     <chr>         <dbl>\n 1 Banks  New South Wales Divisions Yes           37736\n 2 Banks  New South Wales Divisions No            46343\n 3 Banks  New South Wales Divisions Not_Eligible    247\n 4 Banks  New South Wales Divisions NoResponse    20928\n 5 Banks  New South Wales Divisions Total        105254\n 6 Barton New South Wales Divisions Yes           37153\n 7 Barton New South Wales Divisions No            47984\n 8 Barton New South Wales Divisions Not_Eligible    226\n 9 Barton New South Wales Divisions NoResponse    24008\n10 Barton New South Wales Divisions Total        109371\n# … with 740 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(vote_response)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 750   4\n```\n:::\n:::\n\n\nNow the data set has become longer and final dimensions are `750` rows and `4` columns.\n\nI have used pivot_longer to tidy the data set where I have collapse the responses(Yes, No, Not_Eligible, NoResponse and Total) into one column so we can vary them easily and really make sense. So now we can get the divisional level count or area level count easily and we can also plot it easily now in different ways.\n",
    "supporting": [
      "challenge3_ManiShankerKamarapu_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}