{
  "hash": "d2ac027750a82a2ba08d7acce6db064c",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 Attempt\"\nauthor: \"Emma Rasmussen\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"08/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n  - railroads\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n##Reading in the Data/Tidying\n\nReading the data set into R and skipping the first 3 rows so the header includes state, county, and total\n\n::: {.cell}\n\n```{.r .cell-code}\nStateCounty2012OG<-read_excel(\"_data/StateCounty2012.xls\",\n                            skip=3)\nStateCounty2012OG\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,990 × 5\n   STATE     ...2  COUNTY               ...4  TOTAL\n   <chr>     <lgl> <chr>                <lgl> <dbl>\n 1 AE        NA    APO                  NA        2\n 2 AE Total1 NA    <NA>                 NA        2\n 3 AK        NA    ANCHORAGE            NA        7\n 4 AK        NA    FAIRBANKS NORTH STAR NA        2\n 5 AK        NA    JUNEAU               NA        3\n 6 AK        NA    MATANUSKA-SUSITNA    NA        2\n 7 AK        NA    SITKA                NA        1\n 8 AK        NA    SKAGWAY MUNICIPALITY NA       88\n 9 AK Total  NA    <NA>                 NA      103\n10 AL        NA    AUTAUGA              NA      102\n# … with 2,980 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nSelecting for columns that contain variables:\n\n::: {.cell}\n\n```{.r .cell-code}\nStateCounty2012<- select(StateCounty2012OG, \"STATE\", \"COUNTY\", \"TOTAL\")\nStateCounty2012\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,990 × 3\n   STATE     COUNTY               TOTAL\n   <chr>     <chr>                <dbl>\n 1 AE        APO                      2\n 2 AE Total1 <NA>                     2\n 3 AK        ANCHORAGE                7\n 4 AK        FAIRBANKS NORTH STAR     2\n 5 AK        JUNEAU                   3\n 6 AK        MATANUSKA-SUSITNA        2\n 7 AK        SITKA                    1\n 8 AK        SKAGWAY MUNICIPALITY    88\n 9 AK Total  <NA>                   103\n10 AL        AUTAUGA                102\n# … with 2,980 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\nRemoving state employee total rows:\n\n::: {.cell}\n\n```{.r .cell-code}\nStateCounty2012<-filter(StateCounty2012, `COUNTY` !=\"NA\")\nStateCounty2012\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   STATE COUNTY               TOTAL\n   <chr> <chr>                <dbl>\n 1 AE    APO                      2\n 2 AK    ANCHORAGE                7\n 3 AK    FAIRBANKS NORTH STAR     2\n 4 AK    JUNEAU                   3\n 5 AK    MATANUSKA-SUSITNA        2\n 6 AK    SITKA                    1\n 7 AK    SKAGWAY MUNICIPALITY    88\n 8 AL    AUTAUGA                102\n 9 AL    BALDWIN                143\n10 AL    BARBOUR                  1\n# … with 2,920 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\nRenaming the TOTAL column to more accurate describe the variable:\n\n::: {.cell}\n\n```{.r .cell-code}\nStateCounty2012<-rename(StateCounty2012, Total_employees=TOTAL)\nStateCounty2012\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   STATE COUNTY               Total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nThe code below returns the highest and lowest number of counties (with railroad employees) by state.\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(StateCounty2012$STATE)%>%\n  max()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 221\n```\n:::\n\n```{.r .cell-code}\ntable(StateCounty2012$STATE)%>%\n  min()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n## Describe the data\n\nThis data was likely gathered from government employment records or employment records directly from the railroads or Department of Transportation. Cases- counties within states, variables- states, and the number of employees at railroads within each county.\n\nDimensions of the \"tidied\" dataset:\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(StateCounty2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\nThe data set has 2930 rows (counties with railroads) and 3 columns (State, County, and number of employees).\n\n\nThe code below creates a table with a count of counties by state. For example, Florida (FL) has 67 counties with railroads.\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(StateCounty2012$STATE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n AE  AK  AL  AP  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL  IN  KS  KY \n  1   6  67   1  72  15  55  57   8   1   3  67 152   3  99  36 103  92  95 119 \n LA  MA  MD  ME  MI  MN  MO  MS  MT  NC  ND  NE  NH  NJ  NM  NV  NY  OH  OK  OR \n 63  12  24  16  78  86 115  78  53  94  49  89  10  21  29  12  61  88  73  33 \n PA  RI  SC  SD  TN  TX  UT  VA  VT  WA  WI  WV  WY \n 65   5  46  52  91 221  25  92  14  39  69  53  22 \n```\n:::\n:::\n\nI was shocked to see that Texas has 221 counties with people who work for railroads, compared to MA with 12 counties. A quick Google Search says Texas actually has 254 counties. Since Texas has the greatest number of counties with railroad employees, I will look closer at the distribution of employees across Texas counties.\n\n## Provide Grouped Summary Statistics\n\nFiltering the subgroup of New Hampshire counties: (I used to live on the NH border)\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(StateCounty2012, STATE == \"NH\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   STATE COUNTY       Total_employees\n   <chr> <chr>                  <dbl>\n 1 NH    BELKNAP                    2\n 2 NH    CARROLL                   12\n 3 NH    CHESHIRE                  28\n 4 NH    COOS                      19\n 5 NH    GRAFTON                    7\n 6 NH    HILLSBOROUGH             136\n 7 NH    MERRIMACK                  9\n 8 NH    ROCKINGHAM               146\n 9 NH    STRAFFORD                 27\n10 NH    SULLIVAN                   7\n```\n:::\n:::\n\n\nCalculating the Mode:\n\n::: {.cell}\n\n```{.r .cell-code}\nNHTable<-filter(StateCounty2012, STATE == \"NH\")%>%\n  arrange(Total_employees)%>%\n  count(Total_employees)%>%\n  arrange(desc(n))\nNHTable$Total_employees[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7\n```\n:::\n:::\n\nWhile not super helpful, the most common number of employees at NH railroads by county is 7.\n\n\nOther summary statistics for the subgroup of NH counties:\n\n::: {.cell}\n\n```{.r .cell-code}\nStateCounty2012\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,930 × 3\n   STATE COUNTY               Total_employees\n   <chr> <chr>                          <dbl>\n 1 AE    APO                                2\n 2 AK    ANCHORAGE                          7\n 3 AK    FAIRBANKS NORTH STAR               2\n 4 AK    JUNEAU                             3\n 5 AK    MATANUSKA-SUSITNA                  2\n 6 AK    SITKA                              1\n 7 AK    SKAGWAY MUNICIPALITY              88\n 8 AL    AUTAUGA                          102\n 9 AL    BALDWIN                          143\n10 AL    BARBOUR                            1\n# … with 2,920 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\nStateCounty2012%>%\n  filter(STATE == \"NH\") %>%\n  summarize(\"NHmin\"= min(Total_employees), \"NHmax\"= max(Total_employees), \"NHmean\"= mean(Total_employees), \"NHmedian\"= median(Total_employees), \"NHmode\"= mode(Total_employees), \"NHsd\" = sd(Total_employees), \"NHIQR\"= IQR(Total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 7\n  NHmin NHmax NHmean NHmedian NHmode   NHsd NHIQR\n  <dbl> <dbl>  <dbl>    <dbl> <chr>   <dbl> <dbl>\n1     2   146   39.3     15.5 numeric  54.3  20.2\n```\n:::\n:::\n\n\nFinding the county in each state with the largest number of employees:\n\n::: {.cell}\n\n```{.r .cell-code}\nStateCountyLarge<-group_by(StateCounty2012, STATE)%>%\n  arrange(StateCounty2012, (\"STATE\"), desc(\"Total_employees\"))%>%\n  slice(1)\nStateCountyLarge\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 3\n# Groups:   STATE [53]\n   STATE COUNTY        Total_employees\n   <chr> <chr>                   <dbl>\n 1 AE    APO                         2\n 2 AK    ANCHORAGE                   7\n 3 AL    AUTAUGA                   102\n 4 AP    APO                         1\n 5 AR    ARKANSAS                   11\n 6 AZ    APACHE                    270\n 7 CA    ALAMEDA                   346\n 8 CO    ADAMS                     553\n 9 CT    FAIRFIELD                 486\n10 DC    WASHINGTON DC             279\n# … with 43 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nFinding the mean of the largest total employee numbers in each state (this is a pretty useless stat but I was just trying to find some summary statistics from a grouped/sliced data set). I don't love this code, there are too many variables but it's not working when I edit it any more to try to calculate the median etc.  \n\n::: {.cell}\n\n```{.r .cell-code}\nStateMax<-summarize(StateCountyLarge, mt= mean(Total_employees))\nTotalStateMean<-summarize(StateMax, mt=mean(mt))\nprint(TotalStateMean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n     mt\n  <dbl>\n1  93.0\n```\n:::\n:::\n\nThe mean of the largest total employee numbers across the 53 included states/territories is 93.03774 employees.\n\n### Explain and Interpret\n\nI chose NH because I was curious about the distribution of railroad employees by county in that area (I grew up on the NH border). There is lots of variability in NH railroad employment. Rockingham county has 146 employees, while Belknap county has only 2 railroad employees. I then tried to slice out the counties with the most employees by state to see how many employees there are on average at the \"biggest\" railroad counties in each state. I was surprised comparing the NH max to the mean of the largest railroads by county in each state(the second data analyzed that was sliced). I was surprise given the mean number of employees at the \"largest\" railroad/county in each state was only 93, but the max for NH is 146. I don't think of NH has a big state or having a lot of railroads. One thing that might expplain this is that states like Texas (over 100) have more counties than NH (10) skewing the mean (93.0377). In comparison, NH would have larger employment numbers by county given it only has 10 counties. \n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}