{
  "hash": "7686d5a8b056d94748233261a7d1add9",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4\"\nauthor: \"Saaradhaa M\"\ndesription: \"Data wrangling and pivoting\"\ndate: \"08/21/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n    df-print: paged\ncategories:\n  - challenge_4\n  - tidyverse\n  - readxl\n  - lubridate\n  - summarytools\n  - debt_in_trillions\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(lubridate)\nlibrary(summarytools)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Reading in and describing data\n\n::: callout-tip\n## Just trying out pop-up text for fun!\n\nI will be working with the debt in trillions dataset.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in data.\ndebt <- read_excel(\"_data/debt_in_trillions.xlsx\")\n\n# dimensions, column names and basic descriptives.\ndim(debt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 74  8\n```\n:::\n\n```{.r .cell-code}\ncolnames(debt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Year and Quarter\" \"Mortgage\"         \"HE Revolving\"     \"Auto Loan\"       \n[5] \"Credit Card\"      \"Student Loan\"     \"Other\"            \"Total\"           \n```\n:::\n\n```{.r .cell-code}\nsummary(debt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Year and Quarter      Mortgage       HE Revolving      Auto Loan     \n Length:74          Min.   : 4.942   Min.   :0.2420   Min.   :0.6220  \n Class :character   1st Qu.: 8.036   1st Qu.:0.4275   1st Qu.:0.7430  \n Mode  :character   Median : 8.412   Median :0.5165   Median :0.8145  \n                    Mean   : 8.274   Mean   :0.5161   Mean   :0.9309  \n                    3rd Qu.: 9.047   3rd Qu.:0.6172   3rd Qu.:1.1515  \n                    Max.   :10.442   Max.   :0.7140   Max.   :1.4150  \n  Credit Card      Student Loan        Other            Total       \n Min.   :0.6590   Min.   :0.2407   Min.   :0.2960   Min.   : 7.231  \n 1st Qu.:0.6966   1st Qu.:0.5333   1st Qu.:0.3414   1st Qu.:11.311  \n Median :0.7375   Median :0.9088   Median :0.3921   Median :11.852  \n Mean   :0.7565   Mean   :0.9189   Mean   :0.3831   Mean   :11.779  \n 3rd Qu.:0.8165   3rd Qu.:1.3022   3rd Qu.:0.4154   3rd Qu.:12.674  \n Max.   :0.9270   Max.   :1.5840   Max.   :0.4860   Max.   :14.957  \n```\n:::\n\n```{.r .cell-code}\n# check for missing data.\napply(debt, 2, anyNA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nYear and Quarter         Mortgage     HE Revolving        Auto Loan \n           FALSE            FALSE            FALSE            FALSE \n     Credit Card     Student Loan            Other            Total \n           FALSE            FALSE            FALSE            FALSE \n```\n:::\n:::\n\n\nThis dataset has 74 rows and 8 columns. Except for Year and Quarter, all other columns are in numeric format. A quick Google search shows that each row represents different types of debt in the US for that particular year and quarter. Looking at the median values for each column, mortgage debt seems to be the greatest in value (8.412 trillion!), while other debt has the lowest median value (0.3921). There also seems to be no missing data.\n\n## Tidy and Mutate Data\n\nThe data needs to be tidied:\n\n-   Year and Quarter should be split into two separate columns.\n\n-   For consistency, all debt-type columns should have the same number of decimal places.\n\n-   The data would be easier to read if we pivoted the debt-type columns (*N* = 7) such that we only have to look at Year, Quarter, Debt Type and Value.\n\nAt the end of the tidying process, we should have 74 \\* 7 = 514 rows, 4 columns and all decimals to 3 decimal places.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# separate the two columns.\ndebt <- separate(debt, \"Year and Quarter\", into=c(\"year\", \"quarter\"), sep=\":Q\")\n\n# mutate for consistent decimal places.\ndebt <- mutate(debt, across(where(is.numeric), ~ round(., 3)))\n\n# pivot.\ndebt <- debt %>% pivot_longer(cols = where(is.numeric), names_to = \"debt_type\", values_to = \"amount\")\n\n# check new dimensions.\ndim(debt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 518   4\n```\n:::\n:::\n\n\nGreat! Now we have tidy data, where each case is represented by a particular year, quarter, debt_type and associated amount. Moving on to changing column types - we can change quarter to numeric format, debt_type into a factor and year into date format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# change \"quarter\" to numeric.\ndebt$quarter <- as.numeric(debt$quarter)\n\n# change \"debt_type\" to categories.\ndebt$debt_type <- as.factor(debt$debt_type)\n\n# change \"year\" to date.\ndebt$year <- as.Date(debt$year, format = \"%y\")\ndebt$year <- year(debt$year)\n\n# check new dataset.\nprint(summarytools::dfSummary(debt, varnumbers = FALSE, plain.ascii = FALSE, graph.magnif = 0.50, style = \"grid\", valid.col = FALSE), \n      method = 'render', table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>debt</h4>\n<strong>Dimensions</strong>: 518 x 4\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">year\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2011.8 (5.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2003 &le; 2012 &le; 2021</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 9 (0)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">19 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5ggcEzkANpJhSgAAAD9JREFUSMdjYBg6QAk/UBQUFICqVDY2BiIjYxzUqMpRlaMqR1WOqhxVCaGA1YcCcSqB1KjKoaNSiSCAqRwKAADs3zt2bXMgswAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wOC0yOFQxOTo1NzowMCswMDowMAVT4doAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDgtMjhUMTk6NTc6MDArMDA6MDB0DllmAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">quarter\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.5 (1.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 2 &le; 4</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">133</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">25.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">2</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">133</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">25.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">3</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">126</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">24.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">4</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">126</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">24.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACAAAAA3BAMAAACfh1XkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5ggcEzkANpJhSgAAACxJREFUKM9jYKAOUIIDqICyMRQYDTIBDJcKwsFw9osiuhmDTQDDpcPJL5QCAG6iUL14EzQVAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTI4VDE5OjU3OjAwKzAwOjAwBVPh2gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0yOFQxOTo1NzowMCswMDowMHQOWWYAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">debt_type\n[factor]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1. Auto Loan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">2. Credit Card</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">3. HE Revolving</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">4. Mortgage</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">5. Other</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">6. Student Loan</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">7. Total</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 5px 0 7px;margin:0;border:0\" align=\"right\">74</td><td style=\"padding:0 2px 0 0;border:0;\" align=\"left\">(</td><td style=\"padding:0;border:0\" align=\"right\">14.3%</td><td style=\"padding:0 4px 0 2px;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABcAAABZBAMAAAAnVqKPAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5ggcEzkANpJhSgAAAC9JREFUOMtjYCAPKIGAApSjbAwEdOCgWCoIAgLYOIPMbQPinFG3DT+3DZnkTyoAAEyjTKrzlk7DAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTI4VDE5OjU3OjAwKzAwOjAwBVPh2gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0yOFQxOTo1NzowMCswMDowMHQOWWYAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">amount\n[numeric]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 3.4 (4.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0.2 &le; 0.8 &le; 15</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 7.4 (1.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">449 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAFEAAAA7BAMAAADxzns5AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEX////9/v2mpqbw8PD///+xh0SBAAAAAnRSTlMAAHaTzTgAAAABYktHRACIBR1IAAAAB3RJTUUH5ggcEzkANpJhSgAAAFxJREFUSMftzkEKgCAURVGXUK6grjvQ/e8tlJ8DKY1okPDu5KEcUOfmCfa132IyJElJSUlJyT9I4KEMKb6U7Rv3sj1/KOsnujIjm4HMNzaX0lMqpA5sJhl2yhk6ACl3jbo5k4f0AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA4LTI4VDE5OjU3OjAwKzAwOjAwBVPh2gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wOC0yOFQxOTo1NzowMCswMDowMHQOWWYAAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.1)<br/>2022-08-28</p>\n</div>\n```\n:::\n:::\n\n\nOk - we've changed our column types as required, and checked that this was done correctly. From the summary table, we can see that 6 values for quarters 3 and 4 have not been keyed in. I want to look at year and quarter to see which values these are - so that for future analyses using year and quarter, we know which year(s) might not have all the information we need.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndebt %>% select(year, quarter) %>% arrange(desc(quarter), desc(year))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"quarter\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2019\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2018\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2017\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2016\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2015\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2014\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2013\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2012\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2011\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2010\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2009\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2008\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2007\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2006\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2005\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2004\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2003\",\"2\":\"4\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2020\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2019\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2018\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2017\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2016\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2015\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2014\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2013\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2012\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2011\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2010\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2009\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2008\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2007\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2006\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2005\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2004\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2003\",\"2\":\"3\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2020\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2019\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2018\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2017\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2016\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2015\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2014\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2013\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2012\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2011\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2010\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2009\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2008\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2007\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2006\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2005\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2004\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2003\",\"2\":\"2\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2021\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2020\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2019\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2018\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2017\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2016\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2015\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2014\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2013\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2012\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2011\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2010\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2009\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2008\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2007\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2006\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2005\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2004\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"},{\"1\":\"2003\",\"2\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nLooking through the table shows us that the missing values are for 2021 (understandable - the data might not yet be available). This means that our dataset ranges from Q1 of 2003 to Q2 of 2021. When looking at total debt for each year, it might be useful just to look at 2003 to 2020 for completeness.\n",
    "supporting": [
      "SaaradhaaM_Challenge4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}