{
  "hash": "a3cc9949b84d03920c065506e6f8fe38",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Young Soo Choi\"\ndesription: \"Data wrangling: using group() and summarise()\"\ndate: \"08/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nI choosed 'StateCounty2012.xls'file and read it. But it has first 3 rows about title and any others. So I removed the first 3 rows using skip code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nstate2012 <- read_xls(\"_data/StateCounty2012.xls\", skip=3)\nstate2012\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,990 × 5\n   STATE     ...2  COUNTY               ...4  TOTAL\n   <chr>     <lgl> <chr>                <lgl> <dbl>\n 1 AE        NA    APO                  NA        2\n 2 AE Total1 NA    <NA>                 NA        2\n 3 AK        NA    ANCHORAGE            NA        7\n 4 AK        NA    FAIRBANKS NORTH STAR NA        2\n 5 AK        NA    JUNEAU               NA        3\n 6 AK        NA    MATANUSKA-SUSITNA    NA        2\n 7 AK        NA    SITKA                NA        1\n 8 AK        NA    SKAGWAY MUNICIPALITY NA       88\n 9 AK Total  NA    <NA>                 NA      103\n10 AL        NA    AUTAUGA              NA      102\n# … with 2,980 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\ncolnames(state2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"STATE\"  \"...2\"   \"COUNTY\" \"...4\"   \"TOTAL\" \n```\n:::\n:::\n\n\nThis dataset has 2990 rows and 5 columns. And each column name is \"STATE\", \"...2\", \"COUNTY\", \"...4\", \"TOTAL\".\n\n## Describe the data\n\nThis dataset is about the number of workers related to railroad jobs in 2012 I think. And this dataset contains data of 2990 county.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(state2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    STATE             ...2            COUNTY            ...4        \n Length:2990        Mode:logical   Length:2990        Mode:logical  \n Class :character   NA's:2990      Class :character   NA's:2990     \n Mode  :character                  Mode  :character                 \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n     TOTAL         \n Min.   :     1.0  \n 1st Qu.:     7.0  \n Median :    22.0  \n Mean   :   256.9  \n 3rd Qu.:    71.0  \n Max.   :255432.0  \n NA's   :5         \n```\n:::\n:::\n\n\n## Provide Grouped Summary Statistics\n\nI choosed MA and CA because MA is the state where I live in and CA is much bigger state I think. I used filter code to figure out MA's and CA's central tendency numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMA<-filter(state2012, STATE==\"MA\")\nsummary(MA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    STATE             ...2            COUNTY            ...4        \n Length:12          Mode:logical   Length:12          Mode:logical  \n Class :character   NA's:12        Class :character   NA's:12       \n Mode  :character                  Mode  :character                 \n                                                                    \n                                                                    \n                                                                    \n     TOTAL      \n Min.   : 44.0  \n 1st Qu.:101.8  \n Median :271.0  \n Mean   :281.6  \n 3rd Qu.:396.8  \n Max.   :673.0  \n```\n:::\n\n```{.r .cell-code}\nCA<-filter(state2012, STATE==\"CA\")\nsummary(CA)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    STATE             ...2            COUNTY            ...4        \n Length:55          Mode:logical   Length:55          Mode:logical  \n Class :character   NA's:55        Class :character   NA's:55       \n Mode  :character                  Mode  :character                 \n                                                                    \n                                                                    \n                                                                    \n     TOTAL       \n Min.   :   1.0  \n 1st Qu.:  12.5  \n Median :  61.0  \n Mean   : 238.9  \n 3rd Qu.: 200.5  \n Max.   :2888.0  \n```\n:::\n:::\n\n\n### Explain and Interpret\n\n MA has 12 county and average total is 286.1 and CA has 55 county and average total is 238.9. So I figure CA has more county than MA but MA's average total is larger than CA's.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}