{
  "hash": "7db453dbac088a0827a48c1a1a759bfe",
  "result": {
    "markdown": "---\ntitle: \"Challenge 8\"\nauthor: \"Nick Boonstra\"\ndescription: \"Joining Data\"\ndate: \"08/25/2022\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_8\n  - snl\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Introduction\n\nThis is a fun one! Today I am going to be joining, mutating, and analyzing data of *SNL* cast members and seasons.\n\n## Read in data\n\nThe data for this challenge are contained within three related .csv files.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors_orig<-read_csv(\"_data/snl_actors.csv\")\nsnl_casts_orig<-read_csv(\"_data/snl_casts.csv\")\nsnl_seasons_orig<-read_csv(\"_data/snl_seasons.csv\")\n```\n:::\n\n\n### Briefly describe the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,306 × 4\n   aid            url           type  gender \n   <chr>          <chr>         <chr> <chr>  \n 1 Kate McKinnon  /Cast/?KaMc   cast  female \n 2 Alex Moffat    /Cast/?AlMo   cast  male   \n 3 Ego Nwodim     /Cast/?EgNw   cast  unknown\n 4 Chris Redd     /Cast/?ChRe   cast  male   \n 5 Kenan Thompson /Cast/?KeTh   cast  male   \n 6 Carey Mulligan /Guests/?3677 guest andy   \n 7 Marcus Mumford /Guests/?3679 guest male   \n 8 Aidy Bryant    /Cast/?AiBr   cast  female \n 9 Steve Higgins  /Crew/?StHi   crew  male   \n10 Mikey Day      /Cast/?MiDa   cast  male   \n# … with 2,296 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\nsnl_casts_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 614 × 8\n   aid                sid featured first_epid last_epid update…¹ n_epi…² seaso…³\n   <chr>            <dbl> <lgl>         <dbl>     <dbl> <lgl>      <dbl>   <dbl>\n 1 A. Whitney Brown    11 TRUE       19860222        NA FALSE          8   0.444\n 2 A. Whitney Brown    12 TRUE             NA        NA FALSE         20   1    \n 3 A. Whitney Brown    13 TRUE             NA        NA FALSE         13   1    \n 4 A. Whitney Brown    14 TRUE             NA        NA FALSE         20   1    \n 5 A. Whitney Brown    15 TRUE             NA        NA FALSE         20   1    \n 6 A. Whitney Brown    16 TRUE             NA        NA FALSE         20   1    \n 7 Alan Zweibel         5 TRUE       19800409        NA FALSE          5   0.25 \n 8 Sasheer Zamata      39 TRUE       20140118        NA FALSE         11   0.524\n 9 Sasheer Zamata      40 TRUE             NA        NA FALSE         21   1    \n10 Sasheer Zamata      41 FALSE            NA        NA FALSE         21   1    \n# … with 604 more rows, and abbreviated variable names ¹​update_anchor,\n#   ²​n_episodes, ³​season_fraction\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\nsnl_seasons_orig\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 46 × 5\n     sid  year first_epid last_epid n_episodes\n   <dbl> <dbl>      <dbl>     <dbl>      <dbl>\n 1     1  1975   19751011  19760731         24\n 2     2  1976   19760918  19770521         22\n 3     3  1977   19770924  19780520         20\n 4     4  1978   19781007  19790526         20\n 5     5  1979   19791013  19800524         20\n 6     6  1980   19801115  19810411         13\n 7     7  1981   19811003  19820522         20\n 8     8  1982   19820925  19830514         20\n 9     9  1983   19831008  19840512         19\n10    10  1984   19841006  19850413         17\n# … with 36 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\nThe \"actors\" dataframe appears to record every individual who has made an appearance on *Saturday Night Live*, whether that was as a cast member, a guest (including musical guests), or someone with a \"crew\" designation (the meaning of which is not entirely clear). The urls aren't very pretty, so I will remove them from the dataframe at the tidying stage.\n\nThe \"casts\" dataframe focusses on individuals who have appeared as cast members on the show, excluding guests from the list. Specification is made for whether or not a cast member was a featured player (a designation below a full repertory cast member) for a given season, as well as whether or not they served as a \"Weekend Update\" anchor. In certain cases, this dataframe will also give the date of the first and/or last episode on which a given cast member appeared; however, these cases are inconsistent at best. With this being the case, and given the analysis I intend to do, I will be removing these first and last episode columns when I tidy the data. I will also delete and recreate the season_fraction column, just to make sure all values are correct with no mistakes.\n\nLastly, the \"seasons\" dataframe is a simple table of basic data for every season of *SNL*. This table has its own first and last episode dates, for the start and end of each season; these columns are consistent throughout, and I will keep them in the dataframe.\n\n## Tidying Data\n\nIn my own exploratory analysis, I had done most of my tidying and joining together, but both for the sake of clarity and of being careful I will split up those steps here.\n\nThe only real tidying that needs to be done on these dataframes is the removal or cleanup of pesky columns; the data themselves are all tidy. (Recreating the sesason_fraction variable will actually not come until the data are joined.) Additionally, two of the dataframes have columns named \"n_episodes\" which track different variables, so I will rename these to prepare for clean joining.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors<-snl_actors_orig %>% \n  select(-url)\n\nsnl_casts<-snl_casts_orig %>% \n  select(-c(contains(\"epid\"),season_fraction)) %>% \n  rename(\"n_episodes_player\"=\"n_episodes\")\n\nsnl_seasons<-snl_seasons_orig %>% \n  mutate(first_epid=ymd(first_epid)) %>% \n  mutate(last_epid=ymd(last_epid)) %>% \n  rename(\"n_episodes_season\"=\"n_episodes\")\n\nhead(snl_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  aid            type  gender \n  <chr>          <chr> <chr>  \n1 Kate McKinnon  cast  female \n2 Alex Moffat    cast  male   \n3 Ego Nwodim     cast  unknown\n4 Chris Redd     cast  male   \n5 Kenan Thompson cast  male   \n6 Carey Mulligan guest andy   \n```\n:::\n\n```{.r .cell-code}\nhead(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  aid                sid featured update_anchor n_episodes_player\n  <chr>            <dbl> <lgl>    <lgl>                     <dbl>\n1 A. Whitney Brown    11 TRUE     FALSE                         8\n2 A. Whitney Brown    12 TRUE     FALSE                        20\n3 A. Whitney Brown    13 TRUE     FALSE                        13\n4 A. Whitney Brown    14 TRUE     FALSE                        20\n5 A. Whitney Brown    15 TRUE     FALSE                        20\n6 A. Whitney Brown    16 TRUE     FALSE                        20\n```\n:::\n\n```{.r .cell-code}\nhead(snl_seasons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n    sid  year first_epid last_epid  n_episodes_season\n  <dbl> <dbl> <date>     <date>                 <dbl>\n1     1  1975 1975-10-11 1976-07-31                24\n2     2  1976 1976-09-18 1977-05-21                22\n3     3  1977 1977-09-24 1978-05-20                20\n4     4  1978 1978-10-07 1979-05-26                20\n5     5  1979 1979-10-13 1980-05-24                20\n6     6  1980 1980-11-15 1981-04-11                13\n```\n:::\n:::\n\n\n## Join Data\n\n### Keys and Case Counts\n\nBefore we start joining data, we want to make sure we know what the case counts are for each dataframe, and also make sure that we know which variables or combinations of variables serve as the unique keys for each dataframe.\n\n\"snl_actors\" has 2306 rows and 3 columns. \"snl_casts\" has 614 rows and 5 columns. \"snl_seasons\" has 46 rows and 5 columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_actors %>% \n  count(aid) %>% \n  filter(n>1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 2\n# … with 2 variables: aid <chr>, n <int>\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n\n```{.r .cell-code}\nsnl_casts %>% \n  count(aid,sid) %>% \n  filter(n>1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 3\n# … with 3 variables: aid <chr>, sid <dbl>, n <int>\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n\n```{.r .cell-code}\nsnl_seasons %>% \n  count(sid) %>% \n  filter(n>1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 2\n# … with 2 variables: sid <dbl>, n <int>\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n:::\n\n\nThe unique keys are the variables \"aid\" (actor ID) for snl_actors and \"sid\" (season ID) for snl_seasons, with the snl_casts dataframe taking each joint aid-sid case as its unique key.\n\n### Joins\n\n#### snl_casts and snl_seasons\n\nIt would be interesting to see the information from the snl_seasons dataframe listed on the snl_casts dataframe. This can be accomplished with a simple join.\n\nBefore we perform this join, we can preemptively do a simple sanity check. These dataframes only share one key -- the \"sid\" variable -- so the final joined dataframe will have as many columns as snl_casts and snl_seasons combined, less one -- without adding any rows. In other words, this means that we should end up with 614 rows and 9 columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(snl_casts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614\n```\n:::\n\n```{.r .cell-code}\nncol(snl_casts) + ncol(snl_seasons) - 1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9\n```\n:::\n\n```{.r .cell-code}\nsnl_casts_seas <- snl_casts %>% \n  left_join(snl_seasons,by=\"sid\")\n\nsnl_casts_seas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 614 × 9\n   aid           sid featu…¹ updat…² n_epi…³  year first_epid last_epid  n_epi…⁴\n   <chr>       <dbl> <lgl>   <lgl>     <dbl> <dbl> <date>     <date>       <dbl>\n 1 A. Whitney…    11 TRUE    FALSE         8  1985 1985-11-09 1986-05-24      18\n 2 A. Whitney…    12 TRUE    FALSE        20  1986 1986-10-11 1987-05-23      20\n 3 A. Whitney…    13 TRUE    FALSE        13  1987 1987-10-17 1988-02-27      13\n 4 A. Whitney…    14 TRUE    FALSE        20  1988 1988-10-08 1989-05-20      20\n 5 A. Whitney…    15 TRUE    FALSE        20  1989 1989-09-30 1990-05-19      20\n 6 A. Whitney…    16 TRUE    FALSE        20  1990 1990-09-29 1991-05-18      20\n 7 Alan Zweib…     5 TRUE    FALSE         5  1979 1979-10-13 1980-05-24      20\n 8 Sasheer Za…    39 TRUE    FALSE        11  2013 2013-09-28 2014-05-17      21\n 9 Sasheer Za…    40 TRUE    FALSE        21  2014 2014-09-27 2015-05-16      21\n10 Sasheer Za…    41 FALSE   FALSE        21  2015 2015-10-03 2016-05-21      21\n# … with 604 more rows, and abbreviated variable names ¹​featured,\n#   ²​update_anchor, ³​n_episodes_player, ⁴​n_episodes_season\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\ndim(snl_casts_seas)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 614   9\n```\n:::\n:::\n\n\nPerfect!\n\nNow that we've completed this join, we can recreate what had been called the \"season_fraction\" variable in the snl_casts_orig dataframe. This variable recorded the percentage of a given season's episodes in which a given player appeared. For clarity, I am going to call this variable the \"player_appearance_rate\" in this dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_casts_seas<-snl_casts_seas %>% \n  mutate(player_appearance_rate=(n_episodes_player/n_episodes_season))\n\nsnl_casts_seas\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 614 × 10\n   aid           sid featu…¹ updat…² n_epi…³  year first_epid last_epid  n_epi…⁴\n   <chr>       <dbl> <lgl>   <lgl>     <dbl> <dbl> <date>     <date>       <dbl>\n 1 A. Whitney…    11 TRUE    FALSE         8  1985 1985-11-09 1986-05-24      18\n 2 A. Whitney…    12 TRUE    FALSE        20  1986 1986-10-11 1987-05-23      20\n 3 A. Whitney…    13 TRUE    FALSE        13  1987 1987-10-17 1988-02-27      13\n 4 A. Whitney…    14 TRUE    FALSE        20  1988 1988-10-08 1989-05-20      20\n 5 A. Whitney…    15 TRUE    FALSE        20  1989 1989-09-30 1990-05-19      20\n 6 A. Whitney…    16 TRUE    FALSE        20  1990 1990-09-29 1991-05-18      20\n 7 Alan Zweib…     5 TRUE    FALSE         5  1979 1979-10-13 1980-05-24      20\n 8 Sasheer Za…    39 TRUE    FALSE        11  2013 2013-09-28 2014-05-17      21\n 9 Sasheer Za…    40 TRUE    FALSE        21  2014 2014-09-27 2015-05-16      21\n10 Sasheer Za…    41 FALSE   FALSE        21  2015 2015-10-03 2016-05-21      21\n# … with 604 more rows, 1 more variable: player_appearance_rate <dbl>, and\n#   abbreviated variable names ¹​featured, ²​update_anchor, ³​n_episodes_player,\n#   ⁴​n_episodes_season\n# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names\n```\n:::\n:::\n\n\n## Observations\n\nHaving performed these joins and mutations, we can find some interesting information. For example, which cast member had the lowest average appearance rate over the course of their career?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_casts_seas %>% \n  group_by(aid) %>% \n  summarise(mean_app_rate=mean(player_appearance_rate)) %>% \n  arrange(mean_app_rate) %>% \n  slice(1:10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   aid                mean_app_rate\n   <chr>                      <dbl>\n 1 George Coe                0.0417\n 2 Emily Prager              0.0769\n 3 Laurie Metcalf            0.0769\n 4 Michael O'Donoghue        0.167 \n 5 Morwenna Banks            0.2   \n 6 Alan Zweibel              0.25  \n 7 Tom Schiller              0.25  \n 8 Ben Stiller               0.3   \n 9 Tony Rosato               0.538 \n10 Fred Wolf                 0.575 \n```\n:::\n:::\n\n\nThe answer is George Coe, who is an interesting case of having only been credited for his appearance in the very first episode of *SNL*, despite featuring in various subsequent episodes as well.\n\nWe can also visualize how the average appearance rate changed from season to season.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnl_casts_seas %>% \n  group_by(year) %>% \n  summarize(mean_seas_app_rate=mean(player_appearance_rate)) %>% \n  ggplot(aes(year,mean_seas_app_rate)) +\n  geom_point() +\n  geom_line() +\n  theme_bw() +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title=\"Average Player Apperance Rate by Year\",\n       x=\"Year\",\n       y=\"Average Player Appearance Rate\")\n```\n\n::: {.cell-output-display}\n![](challenge8_nickboonstra_files/figure-html/app rate by season-1.png){width=672}\n:::\n:::\n\n\nIt is very interesting to observe that the last six seasons have all had every player feature in every episode! It is also interesting to observe the distinct drop in 1979 and 1980, and I wonder at the reasons behind this drop.\n",
    "supporting": [
      "challenge8_nickboonstra_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}