---
title: "Challenge 5"
author: "Mani Shanker Kamarapu"
description: "Introduction to Visualization"
date: "08/22/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_5
  - AB_NYC_2019
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Read in data

```{r}
AB_NYC_2019 <- read_csv("_data/AB_NYC_2019.csv") %>%
  select(!c("id", "host_id", "neighbourhood", "latitude", "longitude", "minimum_nights", "last_review"))
AB_NYC_2019
```

### Briefly describe the data

```{r}
dim(AB_NYC_2019)
```

```{r}
summary(AB_NYC_2019)
```

## Tidy Data (as needed)

```{r}
AB_NYC_2019 <- replace_na(AB_NYC_2019, list(reviews_per_month = 0))
AB_NYC_2019
```

```{r}
dim(AB_NYC_2019)
```

```{r}
summary(AB_NYC_2019)
```

## Univariate Visualizations

```{r}
ggplot(AB_NYC_2019, aes(price)) + 
  geom_histogram(fill = "blue") + 
  xlim(0,1700) +
  labs(title = "Price of the room", x = "Price", y = "Frequency") + 
  theme_bw()
```

```{r}
ggplot(AB_NYC_2019, aes(number_of_reviews)) + 
  geom_histogram(fill = "lightgreen") + 
  xlim(0,400) +
  labs(title = "No of reviews", x = "Reviews", y = "Frequency") + 
  theme_bw()
```

```{r}
ggplot(AB_NYC_2019, aes(reviews_per_month)) + 
  geom_histogram(fill = "red") + 
  xlim(0,15) +
  labs(title = "Reviews in a month", x = "Monthly reviews", y = "Frequency") + 
  theme_bw()
```

```{r}
ggplot(AB_NYC_2019, aes(availability_365)) + 
  geom_histogram(fill = "orange") + 
  xlim(0,370) +
  labs(title = "Availability of the room", x = "Availability", y = "Frequency") + 
  theme_bw()
```

## Bivariate Visualization(s)

```{r}
ggplot(AB_NYC_2019, aes(price, room_type)) + 
  geom_point() + 
  labs(title = "Price and Room Type", x = "Price", y = "Room Type") + 
  theme_bw()
```
