---
title: "Challenge 8"
author: "Adithya Parupudi"
description: "Joining Data"
date: "08/25/2022"
format:
  html:
    toc: true
    code-copy: true
    code-tools: true
categories:
  - challenge_8
  - Adithya Parupudi
  - snl data
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Read in data

```{r}
snl_actors <- read_csv("_data/snl_actors.csv",show_col_types = FALSE)
snl_casts <- read_csv("_data/snl_casts.csv",show_col_types = FALSE)
snl_seasons <- read_csv("_data/snl_seasons.csv",show_col_types = FALSE)
```

### Briefly describe the data

## Tidy Data (as needed)

Is your data already tidy, or is there work to be done? Be sure to anticipate your end result to provide a sanity check, and document your work here.

```{r}

print(summarytools::dfSummary(snl_actors, 
                              varnumbers = FALSE, 
                              plain.ascii = FALSE, 
                              style = "grid", 
                              graph.magnif = 0.70, 
                              valid.col = FALSE), 
      method = 'render', 
      table.classes = 'table-condensed')

print(summarytools::dfSummary(snl_casts, 
                              varnumbers = FALSE, 
                              plain.ascii = FALSE, 
                              style = "grid", 
                              graph.magnif = 0.70, 
                              valid.col = FALSE), 
      method = 'render', 
      table.classes = 'table-condensed')

print(summarytools::dfSummary(snl_seasons, 
                              varnumbers = FALSE, 
                              plain.ascii = FALSE, 
                              style = "grid", 
                              graph.magnif = 0.70, 
                              valid.col = FALSE), 
      method = 'render', 
      table.classes = 'table-condensed')
```

```{r}
colnames(snl_actors)
colnames(snl_casts)
colnames(snl_seasons)

```

Replacing NA in snl_casts with 0

```{r}
snl_casts<- snl_casts %>% 
  replace_na(list(`first_epid`=0,
                  `last_epid`=0))
```

Removing url column from snl_actors as its not useful it is getting difficult to clean it.

```{r}
snl_actors<- snl_actors %>% 
  select(-url)
```

## Join Data

```{r}
actors_casts <- snl_actors %>%
  inner_join(snl_casts, by = "aid")

fully_joined_dataset <- actors_casts %>%
  inner_join(snl_seasons, by = "sid")

fully_joined_dataset
```
