---
title: "Challenge 1"
author: "Jerin Jacob"
desription: "Reading in data and creating a post"
date: "08/16/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_1
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(readxl)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Read in the Data

```{r}
## Reading Dataset Railroad Employees
railroad <- read_csv("_data/railroad_2012_clean_county.csv")


## Describe the data


railroad
## This is a data set of the rail road employees working in 2930 counties of the states in US in the year of 2012.
## There are 3 variables in the dataset; state, county and total number of employees.

## The minimum number of employees in a county is 1 and the maximum number is 8207

## There are 145 counties where there is only 1 employee working in the rail road department whereas 27 counties have more than 1000 employees

railroad%>%
  select(state)%>%
  n_distinct(.)

## There are 53 distinct values in the variable column named state. This means that there are certain additional values other than the name of the states.

railroad%>%
  select(state)%>%
  distinct()

## The variable 'state' contains all the states along with armed forces,  


```
