{
  "hash": "e48fb014b84a3327bde7ae64c7583738",
  "result": {
    "markdown": "---\ntitle: \"Challenge 4\"\nauthor: \"Ananya Pujary\"\ndescription: \"More data wrangling: pivoting\"\ndate: \"08/18/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_4\n  - fedfundsrate\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(stringr)\nlibrary(skimr)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in data\n\nI'll be reading in the 'FedFundsRate.csv' dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfed_funds_rate<-read_csv(\"_data/FedFundsRate.csv\",\n                        show_col_types = FALSE)\n```\n:::\n\n\n### Briefly describe the data\n\nGenerating an overview of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(fed_funds_rate)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |               |\n|:------------------------|:--------------|\n|Name                     |fed_funds_rate |\n|Number of rows           |904            |\n|Number of columns        |10             |\n|_______________________  |               |\n|Column type frequency:   |               |\n|numeric                  |10             |\n|________________________ |               |\n|Group variables          |None           |\n\n\n**Variable type: numeric**\n\n|skim_variable                | n_missing| complete_rate|    mean|    sd|      p0|     p25|     p50|     p75|    p100|hist  |\n|:----------------------------|---------:|-------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:-----|\n|Year                         |         0|          1.00| 1986.68| 17.17| 1954.00| 1973.00| 1987.50| 2001.00| 2017.00|▅▆▇▇▆ |\n|Month                        |         0|          1.00|    6.60|  3.47|    1.00|    4.00|    7.00|   10.00|   12.00|▇▅▅▅▇ |\n|Day                          |         0|          1.00|    3.60|  6.79|    1.00|    1.00|    1.00|    1.00|   31.00|▇▁▁▁▁ |\n|Federal Funds Target Rate    |       442|          0.51|    5.66|  2.55|    1.00|    3.75|    5.50|    7.75|   11.50|▅▅▇▅▂ |\n|Federal Funds Upper Target   |       801|          0.11|    0.31|  0.14|    0.25|    0.25|    0.25|    0.25|    1.00|▇▁▁▁▁ |\n|Federal Funds Lower Target   |       801|          0.11|    0.06|  0.14|    0.00|    0.00|    0.00|    0.00|    0.75|▇▁▁▁▁ |\n|Effective Federal Funds Rate |       152|          0.83|    4.91|  3.61|    0.07|    2.43|    4.70|    6.58|   19.10|▇▇▃▁▁ |\n|Real GDP (Percent Change)    |       654|          0.28|    3.14|  3.60|  -10.00|    1.40|    3.10|    4.88|   16.50|▁▂▇▂▁ |\n|Unemployment Rate            |       152|          0.83|    5.98|  1.57|    3.40|    4.90|    5.70|    7.00|   10.80|▅▇▅▁▁ |\n|Inflation Rate               |       194|          0.79|    3.73|  2.57|    0.60|    2.00|    2.80|    4.70|   13.60|▇▃▁▁▁ |\n:::\n:::\n\n\nThere are 904 rows and 10 columns in this dataset, all of which are numeric. It includes information on federal fund targets, unemployment rate, real GDP, and inflation rate between the years of 1954 and 2017. There seem to be a lot of missing values.\n\nThe 'Federal Funds Target Rate' varies between 1 and 11.5 percent, and the 'Effective Federal Funds Target Rate' varies between 0.07 and 19.1 percent. 'Real GDP (Percent Change)' lies between -10 and 16.5 percent, 'Unemployment Rate' between 3.4 and 10.8 percent, and 'Inflation Rate' between 0.6 and 13.6 percent.\n\n## Tidy Data and Mutate Variables\n\nI think that converting the missing values to a numeric value like '0.0' would hold some weight and not make much sense, since some of the existing column values are '0.0'. The columns 'Year', 'Month', and 'Day' can be combined to give a comprehensive date for each row.\n\n::: {.cell}\n\n```{.r .cell-code}\nfed_funds_rate$Date <- str_c(fed_funds_rate$Year,\"-\", fed_funds_rate$Month,\"-\",fed_funds_rate$Day)\n\nstr(fed_funds_rate$Date) # the data type is character\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n chr [1:904] \"1954-7-1\" \"1954-8-1\" \"1954-9-1\" \"1954-10-1\" \"1954-11-1\" ...\n```\n:::\n\n```{.r .cell-code}\nDates <- as.Date(fed_funds_rate$Date)\n\nfed_funds_rate$Dates <- as.Date(fed_funds_rate$Date, format=\"%Y-%m-%d\")\n\nstr(fed_funds_rate$Dates) # the data type is date\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Date[1:904], format: \"1954-07-01\" \"1954-08-01\" \"1954-09-01\" \"1954-10-01\" \"1954-11-01\" ...\n```\n:::\n\n```{.r .cell-code}\nfed_funds_rate_final <- fed_funds_rate %>%\n  select(-Date, -Year, -Month, -Day,-'Federal Funds Upper Target', -'Federal Funds Lower Target')\n```\n:::\n\nAfter combining the three columns ('Year','Month','Day') into a new column 'Date', its data type was still 'character'. I used the as.Date() function to convert the values to the date type and stored them in a new column, 'Dates'. I removed the 'Year','Month','Day', and (old) 'Date' columns as well.\n\nWe could remove the 'Federal Funds Upper Target' and 'Federal Funds Lower Target' columns because they have a lot of missing values (801 of 904 total rows) and the 'Federal Funds Target Rate' seems to be providing the same information. I'm also reordering the columns such that 'Dates' is the first one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfed_funds_rate_final <- fed_funds_rate_final[, c(6,1,2,3,4,5)]\n```\n:::\n\n\nBesides this, I think that the dataset is tidy enough to work with.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}