{
  "hash": "be6c54b01b302ca09a1c8a372a31077a",
  "result": {
    "markdown": "---\ntitle: \"Challenge 5\"\nauthor: \"Young Soo Choi\"\ndesription: \"Introduction to Visualization\"\ndate: \"08/22/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_5\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in data\n\nRead Autralian Marriage tidy data file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nab_nyc <- read_csv(\"_data/AB_NYC_2019.csv\",\n                   show_col_types = FALSE)\nab_nyc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 48,895 × 16\n      id name      host_id host_…¹ neigh…² neigh…³ latit…⁴ longi…⁵ room_…⁶ price\n   <dbl> <chr>       <dbl> <chr>   <chr>   <chr>     <dbl>   <dbl> <chr>   <dbl>\n 1  2539 Clean & …    2787 John    Brookl… Kensin…    40.6   -74.0 Privat…   149\n 2  2595 Skylit M…    2845 Jennif… Manhat… Midtown    40.8   -74.0 Entire…   225\n 3  3647 THE VILL…    4632 Elisab… Manhat… Harlem     40.8   -73.9 Privat…   150\n 4  3831 Cozy Ent…    4869 LisaRo… Brookl… Clinto…    40.7   -74.0 Entire…    89\n 5  5022 Entire A…    7192 Laura   Manhat… East H…    40.8   -73.9 Entire…    80\n 6  5099 Large Co…    7322 Chris   Manhat… Murray…    40.7   -74.0 Entire…   200\n 7  5121 BlissArt…    7356 Garon   Brookl… Bedfor…    40.7   -74.0 Privat…    60\n 8  5178 Large Fu…    8967 Shunic… Manhat… Hell's…    40.8   -74.0 Privat…    79\n 9  5203 Cozy Cle…    7490 MaryEl… Manhat… Upper …    40.8   -74.0 Privat…    79\n10  5238 Cute & C…    7549 Ben     Manhat… Chinat…    40.7   -74.0 Entire…   150\n# … with 48,885 more rows, 6 more variables: minimum_nights <dbl>,\n#   number_of_reviews <dbl>, last_review <date>, reviews_per_month <dbl>,\n#   calculated_host_listings_count <dbl>, availability_365 <dbl>, and\n#   abbreviated variable names ¹​host_name, ²​neighbourhood_group,\n#   ³​neighbourhood, ⁴​latitude, ⁵​longitude, ⁶​room_type\n# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names\n```\n:::\n:::\n\n\n\n### Briefly describe the data\n\nThis data set looks like a customer review collected by a company. It contains nearly 50,000 people's review and each data distinguished by their id, neighborhood, and etc.\n\n## Univariate Visualizations\n\nFirst of all, I took a look about their neighbourhood group. I choosed bar graph because it can be recognized easily.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(ab_nyc, neighbourhood_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 2\n  neighbourhood_group     n\n  <chr>               <int>\n1 Bronx                1091\n2 Brooklyn            20104\n3 Manhattan           21661\n4 Queens               5666\n5 Staten Island         373\n```\n:::\n\n```{.r .cell-code}\nggplot(ab_nyc, aes(neighbourhood_group)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](challenge5-youngsoo-choi_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nMost neighbourhood group are Manhattan(21661) and Brooklyn(20104).\n\nNext, I took a closer look at the Manhattan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nab_nyc_man <- ab_nyc%>%\n  filter(neighbourhood_group==\"Manhattan\")\n\ncount(ab_nyc_man, neighbourhood)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 32 × 2\n   neighbourhood          n\n   <chr>              <int>\n 1 Battery Park City     70\n 2 Chelsea             1113\n 3 Chinatown            368\n 4 Civic Center          52\n 5 East Harlem         1117\n 6 East Village        1853\n 7 Financial District   744\n 8 Flatiron District     80\n 9 Gramercy             338\n10 Greenwich Village    392\n# … with 22 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n\n```{.r .cell-code}\nggplot(ab_nyc_man, aes(neighbourhood)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](challenge5-youngsoo-choi_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n32 neighbourhood are in the Manhattan and Harlem's proportion is the largest.\n\n## Bivariate Visualization\n\nNow, I wondered whether availity and amount of review is related. So I made scatter plot regarding availity and reviews per month. I selected review per month to avoid distortion due to subscription period, etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ab_nyc, aes(x=availability_365, y=reviews_per_month)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](challenge5-youngsoo-choi_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nAnything is hard to recognized. It seems like there are no relations between availity and amount of reviews.\n",
    "supporting": [
      "challenge5-youngsoo-choi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}